---
title: "Bifidobacterium analysis"
output: html_notebook
---




```{r}
library(dplyr)
library(ggplot2)
devtools::load_all(reset = FALSE)


```


## load genus abundance
```{r}

genus_path = system.file("data-raw/qiime/generated-files-20190512/taxa/genus.qza", package = "gutzilla")

genus = qiime2R::read_qza(genus_path)$data %>% as.data.frame %>% tibble::rownames_to_column("taxa")  %>% as_tibble()


```



import outliers file
```{r}

outliers = readLines(con="outliers_samples.txt")



```


select based on top 30 read mass genus and remove outliers

```{r}
genus %>%
  #select(1:10) %>%
  mutate_at(-1, ~./sum(.)) -> genus_prop
```


```{r}
top_genus_mass = 
  genus_prop %>% 
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% 
  as.matrix %>% 
  apply(1,sum) %>% 
  sort %>% rev %>% head(30)


genus %>%
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% .[names(top_genus_mass),]-> genus

genus_prop %>%
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% .[names(top_genus_mass),]-> genus_prop
```





### export Bifidobacterium table


```{r}

bifidobacterium_GG = "k__Bacteria;p__Actinobacteria;c__Actinobacteria;o__Bifidobacteriales;f__Bifidobacteriaceae;g__Bifidobacterium"

#bifidobacterium_GG = "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella"

genus_prop[bifidobacterium_GG,] %>%
  reshape2::melt() %>%
  dplyr::rename(SAMPLE_NAME=variable, Bifidobacterium=value) -> bif_df

```

### association with age


```{r}

metadata=read.csv2(system.file("data-raw/Metadata_10317_20191022-112414_curatedv4_VSv1.csv", package = "gutzilla"), stringsAsFactors = FALSE, ) %>% mutate_all(na_if,"")

metadata %>%
  select(SAMPLE_NAME,AGE_CAT) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT!="baby") %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="child","03+",AGE_CAT)) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="teen","10s",AGE_CAT)) %>%
  na.omit() %>%
  mutate(Bifidobacterium=Bifidobacterium>0) %>%
  ggplot()  + geom_bar(aes(x=AGE_CAT, fill=Bifidobacterium), position="fill") +
  scale_fill_brewer("Bifidobacterium", labels=c("Undetected","Detected"), type="qual") + 
  ylab("sample proportion")


metadata %>%
  select(SAMPLE_NAME,AGE_CAT) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT!="baby") %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="child","03+",AGE_CAT)) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="teen","10s",AGE_CAT)) %>%
  na.omit() %>%
  filter(Bifidobacterium>0) %>%
  ggplot()  + 
  geom_violin(aes(x=AGE_CAT, y=Bifidobacterium)) + 
  stat_summary(aes(x=AGE_CAT, y=Bifidobacterium), fun.y="median", geom="point")+
  scale_y_log10()


metadata %>%
  select(SAMPLE_NAME,AGE_CAT) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT!="baby") %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="child","03+",AGE_CAT)) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="teen","10s",AGE_CAT)) %>%
  na.omit() %>%
  filter(Bifidobacterium>0) %>%
  ggplot()  + 
  ggforce::geom_sina(aes(x=AGE_CAT, y=Bifidobacterium), size=.01) + 
  stat_summary(aes(x=AGE_CAT, y=Bifidobacterium),col="red", fun.y="median", geom="point")+
  scale_y_log10()



```




## load enterotypes set from DMM analysis
```{r}

enterotypes = readr::read_csv2("enterotypes_prediction_outliers.csv")[,-1]

enterotypes %>% head



```
## metadata convertion


### diet data
```{r}
diet_variables =
  c("TYPES_OF_PLANTS",
  "DIET_TYPE",
  "ALCOHOL_FREQUENCY",
  "RED_MEAT_FREQUENCY",
  "WHOLE_GRAIN_FREQUENCY",
  "VEGETABLE_FREQUENCY",
  "MEAT_EGGS_FREQUENCY",
  "PREPARED_MEALS_FREQUENCY",
  "FRUIT_FREQUENCY",
  "ONE_LITER_OF_WATER_A_DAY_FREQUENCY",
  "SEAFOOD_FREQUENCY",
  "HOMECOOKED_MEALS_FREQUENCY",
  "HIGH_FAT_RED_MEAT_FREQUENCY",
  "READY_TO_EAT_MEALS_FREQUENCY",
  "SUGAR_SWEETENED_DRINK_FREQUENCY",
  "SUGARY_SWEETS_FREQUENCY",
  "SALTED_SNACKS_FREQUENCY",
  "SPECIALIZED_DIET_FODMAP",
  "SPECIALIZED_DIET_EXCLUDE_DAIRY",
  "SPECIALIZED_DIET_EXCLUDE_NIGHTSHADES",
  "SPECIALIZED_DIET_MODIFIED_PALEO_DIET",
  "SPECIALIZED_DIET_PALEODIET_OR_PRIMAL_DIET",
  "OLIVE_OIL")
```



```{r}




metadata=read.csv2(system.file("data-raw/Metadata_10317_20191022-112414_curatedv4_VSv1.csv", package = "agp"), stringsAsFactors = FALSE, ) %>% mutate_all(na_if,"")

metadata %>%
  #filter(AGE_YEARS >= 18) %>%
  select(SAMPLE_NAME, all_of(diet_variables)) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  select(-value, -set) %>%
  mutate(DIET_TYPE=ifelse(DIET_TYPE=="Vegan","Yes","No")) %>%
  dplyr::rename(SPECIALIZED_DIET_EXCLUDE_ANIMAL = DIET_TYPE) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","Enterotypes_id")) %>%
  na.omit() %>%
  mutate(value=ifelse(value=="false","No",value)) %>%
  mutate(value=ifelse(value=="true","Yes",value)) %>%
  mutate(value = value %>% recode(`Daily` = 1,
                            `Never` = 0,
                            `Occasionally (1-2 times/week)` = 0.5,
                            `Rarely (a few times/month)` = 0.25,
                            `Rarely (less than once/week)` = 0.25,
                            `Regularly (3-5 times/week)` = 0.75,
                            `Less than 5` = 0,
                            `6 to 10` = 0.25,
                            `11 to 20` = 0.5,
                            `21 to 30` = 0.75,
                            `More than 30` = 1,
                            `Yes` = 1,
                            `No` = 0)) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  tidyr::nest(data = -variable) %>% 
  mutate(
    test = purrr::map(data, ~ cor.test(.$Bifidobacterium, .$value, method="spearman")), # S3 list-col
    tidied = purrr::map(test, broom::tidy)
  ) %>% 
  tidyr::unnest(tidied) %>%
  select(variable,estimate,p.value) %>%
  arrange(p.value)







```



### health data

```{r}
health_metadata = c("BMI_CAT",
"ANTIBIOTIC_HISTORY" ,
"ALZHEIMERS",
"AUTOIMMUNE",
"CANCER",
"DIABETES",
"IBD",
"IBS",
"KIDNEY_DISEASE",
"ACID_REFLUX",
"ALLERGIC_TO_I_HAVE_NO_FOOD_ALLERGIES_THAT_I_KNOW_OF",
"CARDIOVASCULAR_DISEASE",
"CDIFF",
"DEPRESSION_BIPOLAR_SCHIZOPHRENIA",
"EPILEPSY_OR_SEIZURE_DISORDER",
"FUNGAL_OVERGROWTH",
"GLUTEN",
"LACTOSE",
"LIVER_DISEASE",
"LUNG_DISEASE",
"MENTAL_ILLNESS",
"MIGRAINE",
"PKU",
"SIBO",
"THYROID")
```



```{r}

metadata %>%
  select(SAMPLE_NAME, all_of(health_metadata)) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  select(-value, -set) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","Enterotypes_id")) %>%
  na.omit() %>%
  mutate(value = ifelse(value=="false","No",value)) %>%
  mutate(value = value %>% recode(`Diagnosed by a medical professional (doctor, physician assistant)` = 1,
                            `I do not have this condition` = 0,
                            `Diagnosed by an alternative medicine practitioner` = 2,
                            `I do not eat gluten because it makes me feel bad` = 1,
                            `I have not taken antibiotics in the past year.` = 0,
                            `Regularly (3-5 times/week)` = 0.75,
                            `I was diagnosed with celiac disease` = 1,
                            `I was diagnosed with gluten allergy (anti-gluten IgG), but not celiac disease` = 1,
                            `Self-diagnosed` = 2,
                            `Obese` = 1,
                            `Normal` = 0,
                            `Yes` = 1,
                            `No` = 0,
                            `true` = 1,
                            `Overweight` = 0,
                            `Underweight` = 0,
                            `Week` = 1,
                            `Year` = 0.25,
                            `Month` = 0.75,
                            `6 months` = 0.5)) %>%
  filter(value!=2) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  tidyr::nest(data = -variable) %>% 
  mutate(
    test = purrr::map(data, ~ cor.test(.$Bifidobacterium, .$value, method="spearman")), # S3 list-col
    tidied = purrr::map(test, broom::tidy)
  ) %>% 
  tidyr::unnest(tidied) %>%
  select(variable,estimate,p.value) %>%
  arrange(p.value)




```

### per age
```{r warning=FALSE}


metadata %>%
  #filter(AGE_YEARS >= 18) %>%
  select(SAMPLE_NAME, all_of(diet_variables), AGE_CAT) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  select(-value, -set) %>%
  mutate(DIET_TYPE=ifelse(DIET_TYPE=="Vegan","Yes","No")) %>%
  dplyr::rename(SPECIALIZED_DIET_EXCLUDE_ANIMAL = DIET_TYPE) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","Enterotypes_id","AGE_CAT")) %>%
  na.omit() %>%
  mutate(value=ifelse(value=="false","No",value)) %>%
  mutate(value=ifelse(value=="true","Yes",value)) %>%
  mutate(value = value %>% recode(`Daily` = 1,
                            `Never` = 0,
                            `Occasionally (1-2 times/week)` = 0.5,
                            `Rarely (a few times/month)` = 0.25,
                            `Rarely (less than once/week)` = 0.25,
                            `Regularly (3-5 times/week)` = 0.75,
                            `Less than 5` = 0,
                            `6 to 10` = 0.25,
                            `11 to 20` = 0.5,
                            `21 to 30` = 0.75,
                            `More than 30` = 1,
                            `Yes` = 1,
                            `No` = 0)) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT != "baby") %>%
  tidyr::nest(data = -c(variable, AGE_CAT)) %>% 
  mutate(
    test = purrr::map(data, ~ cor.test(.$Bifidobacterium, .$value, method="spearman")), # S3 list-col
    tidied = purrr::map(test, broom::tidy),
    n= purrr::map(data, nrow)
  ) %>% 
  tidyr::unnest(tidied,n) %>%
  select(AGE_CAT,variable,estimate,p.value) %>%
  arrange(p.value) -> correlation_bifidobacterium_diet_per_age




```

```{r warning=FALSE}

metadata %>%
  select(SAMPLE_NAME, all_of(health_metadata), AGE_CAT) %>%
  dplyr::rename(FOOD_ALLERGY = ALLERGIC_TO_I_HAVE_NO_FOOD_ALLERGIES_THAT_I_KNOW_OF) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  select(-value, -set) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","Enterotypes_id","AGE_CAT")) %>%
  na.omit() %>%
  mutate(value = ifelse(value=="false","No",value)) %>%
  mutate(value = value %>% recode(`Diagnosed by a medical professional (doctor, physician assistant)` = 1,
                            `I do not have this condition` = 0,
                            `Diagnosed by an alternative medicine practitioner` = 2,
                            `I do not eat gluten because it makes me feel bad` = 1,
                            `I have not taken antibiotics in the past year.` = 0,
                            `Regularly (3-5 times/week)` = 0.75,
                            `I was diagnosed with celiac disease` = 1,
                            `I was diagnosed with gluten allergy (anti-gluten IgG), but not celiac disease` = 1,
                            `Self-diagnosed` = 2,
                            `Obese` = 1,
                            `Normal` = 0,
                            `Yes` = 1,
                            `No` = 0,
                            `true` = 1,
                            `Overweight` = 0,
                            `Underweight` = 0,
                            `Week` = 1,
                            `Year` = 0.25,
                            `Month` = 0.75,
                            `6 months` = 0.5)) %>%
  filter(value!=2) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT != "baby") %>%
  tidyr::nest(data = -c(variable,AGE_CAT)) %>% 
  mutate(
    test = purrr::map(data, ~ cor.test(.$Bifidobacterium, .$value, method="spearman")), # S3 list-col
    tidied = purrr::map(test, broom::tidy),
    n= purrr::map(data, nrow)
  ) %>% 
  tidyr::unnest(tidied,n) %>%
  select(AGE_CAT,variable,estimate,p.value,n) %>%
  mutate(estimate = ifelse(variable=="FOOD_ALLERGY",estimate*-1,estimate)) %>%
  arrange(p.value) -> correlation_bifidobacterium_health_per_age





```


## data viz
```{r fig.height=10, fig.width=10}

correlation_bifidobacterium_diet_per_age  %>%
  mutate(fdr=p.adjust(p.value, method="fdr")) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="child","03+",AGE_CAT)) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="teen","10s",AGE_CAT)) %>%
  ggplot() + geom_bar(aes(x=AGE_CAT,y=estimate, fill=estimate>0, alpha=fdr<0.1), stat="identity") + 
  facet_wrap(~variable %>% gsub("_","\n",.)) +
  scale_fill_brewer("Associated with", labels=c("low Bifids","high Bifids"), type="qual") +
  theme_dark() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("Spearman's rho")


correlation_bifidobacterium_health_per_age %>%
  mutate(fdr=p.adjust(p.value, method="fdr")) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="child","03+",AGE_CAT)) %>%
  mutate(AGE_CAT = ifelse(AGE_CAT=="teen","10s",AGE_CAT)) %>%
  ggplot() + geom_bar(aes(x=AGE_CAT,y=estimate, fill=estimate>0, alpha=fdr<0.1), stat="identity") + 
  facet_wrap(~variable %>% gsub("_","\n",.))+
  scale_fill_brewer("Associated with", labels=c("low Bifids","high Bifids"), type="qual") +
  theme_dark() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("Spearman's rho")



```



```{r}

metadata=read.csv2(system.file("data-raw/Metadata_10317_20191022-112414_curatedv4_VSv1.csv", package = "agp"), stringsAsFactors = FALSE, ) %>% mutate_all(na_if,"")

metadata %>%
  #filter(AGE_YEARS >= 18) %>%
  select(SAMPLE_NAME, all_of(diet_variables), AGE_CAT) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  select(-value, -set) %>%
  mutate(DIET_TYPE=ifelse(DIET_TYPE=="Vegan","Yes","No")) %>%
  dplyr::rename(SPECIALIZED_DIET_EXCLUDE_ANIMAL = DIET_TYPE) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","Enterotypes_id","AGE_CAT")) %>%
  na.omit() %>%
  mutate(value=ifelse(value=="false","No",value)) %>%
  mutate(value=ifelse(value=="true","Yes",value)) %>%
  mutate(value = value %>% recode(`Daily` = 1,
                            `Never` = 0,
                            `Occasionally (1-2 times/week)` = 0.5,
                            `Rarely (a few times/month)` = 0.25,
                            `Rarely (less than once/week)` = 0.25,
                            `Regularly (3-5 times/week)` = 0.75,
                            `Less than 5` = 0,
                            `6 to 10` = 0.25,
                            `11 to 20` = 0.5,
                            `21 to 30` = 0.75,
                            `More than 30` = 1,
                            `Yes` = 1,
                            `No` = 0)) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT != "baby") -> diet_melt


metadata %>%
  select(SAMPLE_NAME, all_of(health_metadata), AGE_CAT) %>%
  dplyr::rename(FOOD_ALLERGY = ALLERGIC_TO_I_HAVE_NO_FOOD_ALLERGIES_THAT_I_KNOW_OF) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  select(-value, -set) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","Enterotypes_id","AGE_CAT")) %>%
  na.omit() %>%
  mutate(value=ifelse(value=="false","No",value)) %>%
  mutate(value=ifelse(value=="true","Yes",value)) %>%
  mutate(value = value %>% recode(`Diagnosed by a medical professional (doctor, physician assistant)` = 1,
                            `I do not have this condition` = 0,
                            `Diagnosed by an alternative medicine practitioner` = 2,
                            `I do not eat gluten because it makes me feel bad` = 1,
                            `I have not taken antibiotics in the past year.` = 0,
                            `Regularly (3-5 times/week)` = 0.75,
                            `I was diagnosed with celiac disease` = 1,
                            `I was diagnosed with gluten allergy (anti-gluten IgG), but not celiac disease` = 1,
                            `Self-diagnosed` = 2,
                            `Obese` = 1,
                            `Normal` = 0,
                            `Yes` = 1,
                            `No` = 0,
                            `true` = 1,
                            `Overweight` = 0,
                            `Underweight` = 0,
                            `Week` = 1,
                            `Year` = 0.25,
                            `Month` = 0.75,
                            `6 months` = 0.5)) %>%
  filter(value!=2) %>%
  merge(bif_df, by="SAMPLE_NAME") %>%
  filter(AGE_CAT != "baby") -> health_melt



rbind(diet_melt, health_melt) %>%
  group_by(AGE_CAT) %>%
  mutate(Bifidobacterium = scale(log10(Bifidobacterium+10^-4))) %>% #ggplot() + geom_boxplot(aes(y=Bifidobacterium, x=AGE_CAT))
  ungroup() %>%
  mutate(value = value%>% as.factor()) %>%
  reshape2::dcast(SAMPLE_NAME + Bifidobacterium + Enterotypes_id + AGE_CAT ~ variable, value.var="value", fill=NA) %>% 
  mutate(Bifidobacterium = ifelse(Bifidobacterium>quantile(Bifidobacterium,2/3), "High",ifelse(Bifidobacterium<quantile(Bifidobacterium, 0.33),"Low","Mid"))) %>% #ggplot() + geom_bar(aes(x=Bifidobacterium))
  #mutate(Bifidobacterium = Bifidobacterium %>% cut(3, label=c("Low","Mid","High"))) %>% ggplot() + geom_bar(aes(x=Bifidobacterium))
  filter(Bifidobacterium != "Mid") %>%
  mutate(Enterotypes_id=Enterotypes_id%>%as.character()) %>%
  #mutate(FOOD_ALLERGY=FOOD_ALLERGY*-1) %>%
  tibble::column_to_rownames("SAMPLE_NAME") -> bif_table
  descrTable(bif_table)
  
  res=compareGroups(Bifidobacterium ~ . -AGE_CAT -Enterotypes_id, data=bif_table, max.xlev = 20)
createTable(res, show.ratio = TRUE)$descr %>% as.data.frame


createTable(res, show.ratio = TRUE, show.p.mul=TRUE) %>% export2word(file="bif_compare_group.docx")

```

### select bacteroides branch
```{r}
# Bacteroides-> Clostridiales : c(11,15,6,8,10,3,4,2, 1, 5)

rbind(diet_melt, health_melt) %>%
  group_by(AGE_CAT) %>%
  mutate(Bifidobacterium = scale(log10(Bifidobacterium+10^-4))) %>% #ggplot() + geom_boxplot(aes(y=Bifidobacterium, x=AGE_CAT))
  ungroup() %>%
  mutate(value = value%>% as.factor()) %>%
  reshape2::dcast(SAMPLE_NAME + Bifidobacterium + Enterotypes_id + AGE_CAT ~ variable, value.var="value", fill=NA) %>% 
  mutate(Bifidobacterium = ifelse(Bifidobacterium>quantile(Bifidobacterium,2/3), "High",ifelse(Bifidobacterium<quantile(Bifidobacterium, 0.33),"Low","Mid"))) %>% #ggplot() + geom_bar(aes(x=Bifidobacterium))
  #mutate(Bifidobacterium = Bifidobacterium %>% cut(3, label=c("Low","Mid","High"))) %>% ggplot() + geom_bar(aes(x=Bifidobacterium))
  filter(Bifidobacterium != "Mid") %>%
  mutate(Enterotypes_id=Enterotypes_id%>%as.character()) %>%
  #mutate(FOOD_ALLERGY=FOOD_ALLERGY*-1) %>%
  tibble::column_to_rownames("SAMPLE_NAME") -> bif_table
  descrTable(bif_table)
  
  res=compareGroups(Bifidobacterium ~ . -AGE_CAT -Enterotypes_id, data=bif_table, max.xlev = 20)
  res_bacteroides=compareGroups(Bifidobacterium ~ . -AGE_CAT -Enterotypes_id, data=bif_table, max.xlev = 20, subset = Enterotypes_id %in% c(11,15,6,8,10,3,4,2))
createTable(res_bacteroides, show.ratio = TRUE)$descr %>% as.data.frame
res_prevotella=compareGroups(Bifidobacterium ~ . -AGE_CAT -Enterotypes_id, data=bif_table, max.xlev = 20, subset = Enterotypes_id %in% c(7,17,16,14,18))

bacteroides_tab = createTable(res_bacteroides, show.ratio = TRUE, show.p.mul=TRUE, show.p.overall = FALSE)

prevotella_tab  = createTable(res_prevotella,  show.ratio = TRUE, show.p.mul=TRUE, show.p.overall = FALSE)

all_tab         = createTable(res,             show.ratio = TRUE, show.p.mul=TRUE, show.p.overall = FALSE) 


cbind(BACTEROIDES=bacteroides_tab, PREVOTELLA=prevotella_tab) %>% export2word(file="bif_compare_group_strata2.docx")


data.frame(bacteroides_tab$descr, branch="bacteroides") %>% 
  as.data.frame %>%
  tibble::rownames_to_column("variable") %>%
  rbind(data.frame(prevotella_tab$descr,branch="prevotella") %>% as.data.frame %>% tibble::rownames_to_column("variable")) %>%
  select(variable,OR,p.ratio, branch) %>%
  filter(OR != "Ref.") %>%
  tidyr::separate(OR, into=c("OR","a"), sep = "\\[") %>%
  mutate(OR = OR %>% as.numeric) %>%
  select(-a) %>%
  reshape2::dcast(variable~branch, value.var = "OR") %>%
  ggplot() + geom_point(aes(x=bacteroides,y=prevotella)) + 
  scale_x_continuous(trans="log2") +scale_y_continuous(trans="log2") +
  geom_abline(slope=1, intercept = 0)


data.frame(bacteroides_tab$descr, branch="bacteroides") %>% 
  as.data.frame %>%
  tibble::rownames_to_column("variable") %>%
  rbind(data.frame(prevotella_tab$descr,branch="prevotella") %>% as.data.frame %>% tibble::rownames_to_column("variable")) %>%
  select(variable,OR,p.ratio, branch) %>%
  filter(OR != "Ref.") %>%
  tidyr::separate(OR, into=c("OR","a"), sep = "\\[") %>%
  mutate(OR = OR %>% as.numeric) %>%
  select(-a) %>%
  reshape2::dcast(variable~branch, value.var = "OR") %>%
  filter(abs(log2(bacteroides/prevotella))>1) %>% pull(variable) -> select_variable
```


```{r fig.height=10, fig.width=8}
data.frame(bacteroides_tab$descr, branch="bacteroides") %>% 
  as.data.frame %>%
  tibble::rownames_to_column("variable") %>%
  rbind(data.frame(prevotella_tab$descr,branch="prevotella") %>% as.data.frame %>% tibble::rownames_to_column("variable")) %>%
  select(variable,OR,p.ratio, branch) %>%
  filter(OR != "Ref.") %>%
  tidyr::separate(OR, into=c("OR","a"), sep = "\\[") %>%
  mutate(OR = OR %>% as.numeric, p.ratio = p.ratio %>% as.character %>% gsub("<","",.) %>% as.numeric) %>%
  select(-a) %>%
  na.omit() %>%
  ggplot() + geom_bar(aes(y=OR,alpha=p.ratio<0.05,fill=branch,x=variable), stat="identity", position="dodge")+
  scale_y_continuous(trans="log2") +
  coord_flip() + facet_wrap(~branch)
```


```{r fig.height=5, fig.width=8}
data.frame(bacteroides_tab$descr, branch="bacteroides") %>% 
  as.data.frame %>%
  tibble::rownames_to_column("variable") %>%
  rbind(data.frame(prevotella_tab$descr,branch="prevotella") %>% as.data.frame %>% tibble::rownames_to_column("variable")) %>%
  select(variable,OR,p.ratio, branch) %>%
  filter(OR != "Ref.") %>%
  tidyr::separate(OR, into=c("OR","a"), sep = "\\[") %>%
  mutate(OR = OR %>% as.numeric, p.ratio = p.ratio %>% as.character %>% gsub("<","",.) %>% as.numeric) %>%
  select(-a) %>%
  na.omit() %>%
  filter(variable %in% select_variable) %>%
  ggplot() + geom_bar(aes(y=OR,alpha=p.ratio<0.05,fill=branch,x=variable), stat="identity", position="dodge")+
  scale_y_continuous(trans="log2") +
  coord_flip() + facet_wrap(~branch)


```


## by country of birth

```{r}


data("UNSD_countries")

metadata = readr::read_csv2(system.file("data-raw/Metadata_10317_20191022-112414_curatedv4_VSv1.csv", package = "agp"))

#to do: check issue parsing IBD variables

colnames(metadata) = stringr::str_to_lower(colnames(metadata))



metadata %>%
  select(country_of_birth) %>%
  merge(UNSD_countries %>% 
          select(`Country or Area`, `Sub-region Name`, `Region Name`) %>% 
          mutate(`Country or Area` =  gsub("United Kingdom of Great Britain and Northern Ireland", "United Kingdom", `Country or Area`)) %>% 
          mutate(`Country or Area` =  gsub("United States of America", "USA", `Country or Area`)) %>%
          mutate(`Sub-region Name` =  ifelse(`Sub-region Name` %in% c("Central Asia", "Southern Asia"), "Central and Southern Asia",`Sub-region Name`)) %>%
          mutate(`Sub-region Name` =  ifelse(`Sub-region Name` %in% c("Melanesia", "Micronesia","Polynesia"), "Oceania (others)",`Sub-region Name`)), 
        by.x="country_of_birth", by.y="Country or Area") %>% 
  group_by(`Region Name`,`Sub-region Name`) %>% summarise(n=n()) %>%
  ungroup() %>%
  ggplot() + geom_bar(aes(y=n, x=`Sub-region Name`), stat="identity") + scale_y_log10() +
  facet_wrap(~`Region Name`, scales = "free_x", nr=1) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  xlab("Region of Birth\n(United Nations-m49)") +
  ylab("Number of stool sample")
  
ggsave("Region_of_birth.pdf")

metadata <- metadata %>%
  merge(UNSD_countries %>% 
          select(`Country or Area`, `Sub-region Name`, `Region Name`) %>% 
          mutate(`Country or Area` =  gsub("United Kingdom of Great Britain and Northern Ireland", "United Kingdom", `Country or Area`)) %>% 
          mutate(`Country or Area` =  gsub("United States of America", "USA", `Country or Area`)) %>%
          mutate(`Sub-region Name` =  ifelse(`Sub-region Name` %in% c("Central Asia", "Southern Asia"), "Central and Southern Asia",`Sub-region Name`)) %>%
          mutate(`Sub-region Name` =  ifelse(`Sub-region Name` %in% c("Melanesia", "Micronesia","Polynesia"), "Oceania (others)",`Sub-region Name`)), 
        by.x="country_of_birth", by.y="Country or Area")
  



```



## Bifidobacterium in Curated Metagenomics db



```{r}

load(system.file("data-raw/curatedMetaG/curated_v3_otu_tax.rda", package = "gutzilla"))


```


```{r}

sampleMetadata %>%
  select(age, sample_id, number_reads) %>% head


```



```{r}

OTU %>%
  merge(TAX %>% as.data.frame() %>% select(Genus), by="row.names") %>%
  select(-Row.names) %>%
  group_by(Genus) %>%
  summarise_all(sum) -> curated_v3_genus






OTU %>%
  unclass() %>%
  as.matrix() %>%
  merge(TAX %>% as.data.frame() %>% select(Genus,Species), by="row.names") %>%
  filter(Genus=="Bifidobacterium") %>% 
  select(-Row.names,-Genus) %>%
  mutate(Species = Species %>% as.character()) %>%
  mutate(Species = ifelse(Species %in% c("Bifidobacterium adolescentis",
                                                     "Bifidobacterium breve",
                                                     "Bifidobacterium bifidum",
                                                     "Bifidobacterium longum"), Species, "others Bifidobacterium")) %>%
  group_by(Species) %>%
  summarise_all(sum) -> curated_v3_Bif_species



```



```{r}
curated_v3_genus %>%
  filter(Genus %in% c("Bifidobacterium","Bacteroides")) %>%
  tibble::column_to_rownames("Genus") %>%
  t() %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("sample_id") %>%
  merge(sampleMetadata %>% select(age, sample_id, number_reads), by="sample_id") %>%
  mutate(log_ratio=log2((Bifidobacterium+1)/(Bacteroides+1))) %>%
  arrange(age) %>%
  mutate(log_ratio_rmean = zoo::rollmedian(log_ratio, 250, align = "right", fill = NA),
         age_rmean = zoo::rollmean(age, 250, align = "right", fill = NA)) %>%
  ggplot() + geom_line(aes(x=age_rmean+1, y=log_ratio_rmean)) + scale_x_log10()


p_bif_genus = curated_v3_genus %>%
  filter(Genus %in% c("Bifidobacterium","Bacteroides")) %>%
  tibble::column_to_rownames("Genus") %>%
  t() %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("sample_id") %>%
  merge(sampleMetadata %>% select(age, sample_id, number_reads), by="sample_id") %>%
  filter(!is.na(age)) %>%
  mutate(log_ratio=log2((Bifidobacterium+1)/(Bacteroides+1))) %>%
  arrange(age) %>%
  mutate(log_ratio_rmean = zoo::rollmean(log_ratio, 1000, align = "right", fill = NA),
         log_ratio_q25 = zoo::rollapply(log_ratio, 1000, FUN=function(x){quantile(x,0.25)}, align = "right", fill = NA),
         log_ratio_q75 = zoo::rollapply(log_ratio, 1000, FUN=function(x){quantile(x,0.75)}, align = "right", fill = NA),
         age_rmean = zoo::rollmean(age, 1000, align = "right", fill = NA)) %>%
  na.omit() %>%
  ggplot() +
  geom_smooth(aes(x=age_rmean+1, y=log_ratio_rmean), se=FALSE) + 
  geom_smooth(aes(x=age_rmean+1, y=log_ratio_q25), se=FALSE, col="grey50") +
  geom_smooth(aes(x=age_rmean+1, y=log_ratio_q75), se=FALSE, col="grey50") +
  scale_y_continuous("Bifidobacterium Bacteroides ratio (log2)") + scale_x_log10("Age (Years)") +
  geom_hline(yintercept = 0, linetype=2) +
  theme_classic()



curated_v3_Bif_species %>%
  mutate_if(is.numeric, function(x) x/sum(x)) %>%
  tibble::column_to_rownames("Species") %>%
  t() %>%
  as.data.frame() -> curated_v3_Bif_species_prop
```


```{r }
curated_v3_Bif_species_prop %>%
  tibble::rownames_to_column("sample_id") %>%
  merge(sampleMetadata %>% select(age, sample_id), by="sample_id") %>%
  reshape2::melt(id.vars=c("sample_id","age")) %>%
  mutate(value=ifelse(is.na(value),0,value)) %>%
  mutate(detection = ifelse(value>0,1,0)) %>%
  arrange(age) %>%
  group_by(variable) %>%
  mutate(rprop = zoo::rollmean(value, 1000, align = "right", fill = NA),
         rprev = zoo::rollmean(detection, 1000, align = "right", fill = NA)) -> curated_v3_Bif_species_stat



p_bif_specis_prop = curated_v3_Bif_species_stat %>%
  na.omit() %>%
  ggplot() + 
  geom_smooth(aes(x=age+1,y=rprop, group=variable, color=variable), se = FALSE) +  
  scale_y_log10("Proportion within Bifidobacterium (%)", labels=scales::percent) + scale_x_log10("Age (Years)") +
  scale_color_brewer("", type="qual") +
  theme_classic()

 p_bif_specis_prev = curated_v3_Bif_species_stat %>%
   na.omit() %>%
   ggplot() + 
  geom_smooth(aes(x=age+1,y=rprev, group=variable, color=variable), se = FALSE) +  
  scale_y_log10("Prevalence (%)", labels=scales::percent) + scale_x_log10("Age (Years)") +
  scale_color_brewer("", type="qual") +
  theme_classic()



```



```{r fig.height=4, fig.width=10}

cowplot::plot_grid(p_bif_genus, p_bif_specis_prop, align = "v", ncol = 2, rel_widths = c(1,1.7))


```



## Bifidobacterium in progenome


```{r}



breve   = readr::read_tsv(system.file("data-raw/bifidobacterium_progenome/specI_v3_Cluster1098.eggNOG_groups.tsv", package = "gutzilla"))
longum  = readr::read_tsv(system.file("data-raw/bifidobacterium_progenome/specI_v3_Cluster1099.eggNOG_groups.tsv", package = "gutzilla"))
ado     = readr::read_tsv(system.file("data-raw/bifidobacterium_progenome/specI_v3_Cluster2703.eggNOG_groups.tsv", package = "gutzilla"))
bifidum = readr::read_tsv(system.file("data-raw/bifidobacterium_progenome/specI_v3_Cluster3116.eggNOG_groups.tsv", package = "gutzilla"))

  
bif_progenome_eggnog =
rbind(data.frame(breve,species="Bifidobacterium breve"),
  data.frame(longum,species="Bifidobacterium longum"),
  data.frame(ado,species="Bifidobacterium adolescentis"),
  data.frame(bifidum,species="Bifidobacterium bifidum")) 
  

bif_progenome_eggnog %>%
  select(species,BIOSAMPLE_ID, EGGNOG_OGS, EGGNOG_FREE_TEXT_DESCRIPTION) %>%
  group_by(EGGNOG_OGS) %>%
  summarise(n=n()) %>%
  arrange(desc(n))

bif_progenome_eggnog %>%
  select(species,BIOSAMPLE_ID, EGGNOG_OGS, EGGNOG_FREE_TEXT_DESCRIPTION) %>%
  reshape2::dcast(EGGNOG_OGS~BIOSAMPLE_ID) %>%
  tibble::column_to_rownames("EGGNOG_OGS") %>%
  as.matrix() %>% heatmap()


bif_progenome_eggnog %>%
  filter(!is.na(CAZY)) %>%
  #select(species,BIOSAMPLE_ID, EGGNOG_OGS, EGGNOG_FREE_TEXT_DESCRIPTION, CAZY) %>%
  select(species,BIOSAMPLE_ID,EGGNOG_OGS, CAZY) %>%
  unique() %>%
  group_by(species,EGGNOG_OGS) %>%
  mutate(eggnog_by_species=n()) %>%
  ungroup() %>%
  group_by(EGGNOG_OGS) %>%
  filter(!all(eggnog_by_species>10)) %>%
  filter(any(eggnog_by_species>20)) %>%
  ungroup() %>%
  mutate(EGGNOG_OGS = EGGNOG_OGS %>% forcats::fct_reorder(eggnog_by_species) ) %>%
  ggplot() + 
  geom_tile(aes(x=BIOSAMPLE_ID,y=CAZY)) + 
  theme_classic() +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),  axis.ticks.y=element_blank()) +
  facet_wrap(~species, nrow = 1, scales = "free_x")
  
  
  

```




