---
title: "apply gut microbiota healthy index to curated metaG DB"
output: html_notebook
---





```{r}

library(phyloseq)
devtools::load_all()
library(magrittr)
library(forcats)

load(system.file("data-raw/curatedMetaG/curatedMetaGData.rda", package = "agp"))

MN_species = readLines(system.file("data-raw/MN_species.txt", package = "agp"))
MH_species = readLines(system.file("data-raw/MH_species.txt", package = "agp"))

```

```{r}

load("curatedMetaG_data.rda")
```



```{r eval=FALSE, include=FALSE}

curatedMetaG_data %>% 
  mutate(Genus=fct_explicit_na(Genus, na_level = ""),
         Family=fct_explicit_na(Family, na_level = ""), 
         Species = fct_explicit_na(Species, na_level = "") ) %>%
  group_by(Kingdom,Phylum,Class,Order,Family,Genus,Species) %>%
  select(-Row.names) %>%
  summarise_all(sum) %>%
  reshape2::melt(id.vars=c("Kingdom","Phylum","Class","Order","Family","Genus","Species")) %>%
  mutate(value=round(value*1000,0)) %>%
  reshape2::dcast(Kingdom+Phylum+Class+Order+Family+Genus+Speceies~variable) -> species_count



```

```{r}


curatedMetaG_data$Species %>% na.omit %>% View()

MH_species_metagenome =
curatedMetaG_data %>% 
  mutate(Species = paste0("s__",Species)) %>% #pull(Species)
  filter(Species %in% c(MH_species)) %>%
  select(-Kingdom,-Phylum,-Class,-Order,-Family,-Genus,-Species) %>%
  tibble::column_to_rownames("Row.names")

MN_species_metagenome =
curatedMetaG_data %>% 
  mutate(Species = paste0("s__",Species)) %>% #pull(Species)
  filter(Species %in% c(MN_species)) %>%
  select(-Kingdom,-Phylum,-Class,-Order,-Family,-Genus,-Species) %>%
  tibble::column_to_rownames("Row.names")
  

```


## GMHI computation

```{r}


output_file = 'GMHI_output.csv'

alpha <- function(x){sum((log(x[x>0]))*(x[x>0]))*(-1)}

MH_shannon <- apply((MH_species_metagenome/100), 2, alpha) 

MN_shannon <- apply((MN_species_metagenome/100), 2, alpha) 





# Richness of Health-prevalent species

# Richness of Health-scarce species

R_MH <- apply(MH_species_metagenome, 2, function(i) (sum(i > 0))) 

R_MN <- apply(MN_species_metagenome, 2, function(i) (sum(i > 0)))





# Median RMH from 1% of the top-ranked samples

# Median RMN from 1% of the bottom-ranked samples

# Supplementary Methods for further details

MH_prime <- 7

MN_prime <- 31





# Collective abundance of Health-prevalent species

# Collective abundance of Health-scarce species

psi_MH <- ((R_MH/MH_prime)*MH_shannon) 

psi_MN <- ((R_MN/MN_prime)*MN_shannon)



GMHI <- data.frame(log10((psi_MH+0.00001)/(psi_MN+0.00001))) # 0.00001 added to avoid having the denominator as 0

colnames(GMHI) <- c("GMHI")



if (file.exists(output_file)){

	file.remove(output_file)

}

write.csv(GMHI, file=output_file) # Saving GMHI results as 'GMHI_output.csv'. User should change the path to the appropriate directory.




```





