---
title: "curated Metagenomics data enterotyping"
output: html_notebook
---


```{r}

library(phyloseq)
devtools::load_all()
library(magrittr)


```



```{r}

load(system.file("data-raw/curatedMetaG/curatedMetaGData.rda", package = "gutzilla"))


```



```{r}

df = otu_table(curatedMetaG_phyloseq) %>%
  merge(tax_table(curatedMetaG_phyloseq), by="row.names")

curatedMetaG_data = df

save(curatedMetaG_data, file="curatedMetaG_data.rda")

tax_table(curatedMetaG_phyloseq) %>% head

```



```{r}
load("curatedMetaG_data.rda")
load("top_genus_mass.rda")
```


```{r}
curatedMetaG_data %>%
  mutate(Genus=forcats::fct_explicit_na(Genus, na_level = ""),
         Family=forcats::fct_explicit_na(Family, na_level = "")) %>%
  group_by(Kingdom,Phylum,Class,Order,Family,Genus) %>%
  select(-Row.names,-Species) %>%
  summarise_all(sum) %>%
  reshape2::melt(id.vars=c("Kingdom","Phylum","Class","Order","Family","Genus")) %>%
  mutate(value=round(value*1000,0)) %>%
  reshape2::dcast(Kingdom+Phylum+Class+Order+Family+Genus~variable) -> genus_count

curatedMetaG_data %>%
  mutate(taxa=paste0("k__",Kingdom,";p__",Phylum,";c__",Class,";o__",Order,";f__",Family,";g__",Genus)) %>%
  filter(Class=="Mollicutes") %>% pull(taxa)

genus_count %>% 
  mutate(taxa=paste0("k__",Kingdom,";p__",Phylum,";c__",Class,";o__",Order,";f__",Family,";g__",Genus)) %>%
  #filter(taxa ==  "k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__;g__")
  #select(taxa) %>%
  filter(taxa %in% names(top_genus_mass)|
           Genus=="Dialister"|
           Genus=="Phascolarctobacterium"|
           taxa == "k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Clostridiales_noname;g__Clostridiales_noname"|
           taxa == "k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Ruminococcaceae;g__Ruminococcaceae_noname"|
           taxa == "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Rikenellaceae;g__Rikenellaceae_noname"|
           taxa == "k__Bacteria;p__Firmicutes;c__Erysipelotrichia;o__Erysipelotrichales;f__Erysipelotrichaceae;g__Erysipelotrichaceae_noname"|
           taxa == "k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Lachnospiraceae;g__Lachnospiraceae_noname") %>%
  select(-Kingdom,-Phylum,-Class,-Order,-Family,-Genus) %>%
  tibble::column_to_rownames("taxa") -> genus_count_dominant
```


```{r}

#alpha_shannon_curated <- phyloseq::estimate_richness(curatedMetaG_phyloseq, measures = "Shannon")

alpha_shannon_curated <-vegan::diversity(genus_count[,-c(1:6)], MARGIN = 2)

```

```{r eval=FALSE, include=FALSE}

names(top_genus_mass)

```



```{r}

sample_to_select = names(which(apply(genus_count_dominant,2,sum) / genus_count %>%
  select(-Kingdom,-Phylum,-Class,-Order,-Family,-Genus) %>%
  apply(2,sum)  > 0.3))

#genus_count_dominant=genus_count_dominant[,1:100]

genus_count_dominant = genus_count_dominant[,sample_to_select]
```


```{r}



source("enterotyping_curatedmetaG.R")
save(fit_genus_list_curated, file="fit_genus_list_curated.rda")


```


```{r}
names(lplc) = as.character(1:5)
as_tibble(lplc)  %>% tibble::rowid_to_column("k") %>% reshape2::melt(id.vars="k") %>% ggplot() + geom_line(aes(x=k,y=value,group=variable))
```


```{r fig.height=6, fig.width=12}

heatmapdmn(t(genus_count_dominant),fit_genus_list_curated[[1]][[1]],fit_genus_list_curated[[1]][[best_genus_lplc]])

###################################################
### code chunk number 11: posterior-mean-diff
###################################################
p0 <- fitted(fit_genus_list_curated[[1]][[1]], scale=TRUE)     # scale by theta
pbest <- fitted(fit_genus_list_curated[[1]][[best_genus_lplc]], scale=TRUE)
colnames(pbest) <- paste("M", 1:best_genus_lplc, sep="")
(meandiff <- colSums(abs(pbest - as.vector(p0))))
sum(meandiff)


###################################################
### code chunk number 12: table-1
###################################################
diff <- rowSums(abs(pbest - as.vector(p0)))
o <- order(diff, decreasing=TRUE)
cdiff <- cumsum(diff[o]) / sum(diff)
df_curated <- head(cbind(Mean=p0[o], pbest[o,], diff=diff[o], cdiff), 30)
df_curated %>% as.data.frame()

#df_curated = df %>% as.data.frame()

df_curated %>% as.data.frame() %>%
  tibble::rownames_to_column("taxa") %>%
  reshape2::melt(id.vars="taxa") %>%
  filter(!variable %in% c("Mean","diff","cdiff")) %>%
  #group_by(taxa) %>%
  #mutate(total = sum(value)) %>%
  #mutate(value=value/total) %>%
  ggplot() + geom_tile(aes(x=variable,y=taxa,fill=value)) + scale_fill_viridis_c()

```


```{r fig.height=5, fig.width=12}

df_curated %>%
  select(-diff,-cdiff,-Mean) %>%
  mutate_at(1:12,~log10(.)) %>%
  t %>%
  as.data.frame %>%
  ade4::dudi.pca(scannf = F,nf=3) %>% .$li %>% ade4::s.label()

df_curated %>%
  select(-diff,-cdiff,-Mean) %>%
  tibble::rownames_to_column("taxa") %>%
  as_tibble %>%
  .[c(1:3,6,10),] %>%
  reshape2::melt(id.vars="taxa") %>%
  group_by(variable) %>%
  mutate(ymax=cumsum(value)) %>%
  mutate(ymin=c(0, head(ymax, n=-1))) %>%
  #ggplot() + geom_bar(aes(y=value,x=variable,fill=taxa),stat="identity") 
  ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=taxa %>% strsplit(x=.,split=";") %>% sapply(function(x)x[6])  )) + 
  geom_rect() +      
  coord_polar(theta="y") + 
  facet_wrap(~variable) + 
  xlim(c(2, 4)) + theme_void() +
  scale_fill_brewer("",type="qual")



```

```{r}

curatedMetaG_metadata %>%
  select(age,age_category,non_westernized,BMI) %>%
  merge(enterotypes_curated, by="row.names") %>%
  filter(age_category != "newborn") %>%
  group_by(age_category) %>%
  mutate(total=n()) %>%
  group_by(age_category,Enterotypes_id,total) %>%
  summarise(prop=n()) %>%
  mutate(prop=prop/total) %>%
  ungroup() %>%
  group_by(Enterotypes_id) %>%
  mutate(prop2=sum(prop)) %>%
  mutate(prop=prop/prop2) %>%
  ggplot() + geom_tile(aes(x=Enterotypes_id %>% as.character(),y=age_category,fill=prop)) + scale_fill_viridis_c()

curatedMetaG_metadata %>%
  select(age,age_category,non_westernized,BMI) %>%
  merge(enterotypes_curated, by="row.names") %>%
  filter(age_category != "newborn") %>%
  group_by(non_westernized) %>%
  mutate(total=n()) %>%
  group_by(non_westernized,Enterotypes_id,total) %>%
  summarise(prop=n()) %>%
  mutate(prop=prop/total) %>%
  ungroup() %>%
  group_by(Enterotypes_id) %>%
  mutate(prop2=sum(prop)) %>%
  mutate(prop=prop/prop2) %>%
  ggplot() + geom_tile(aes(x=Enterotypes_id %>% as.character(),y=non_westernized,fill=prop)) + scale_fill_viridis_c()


curatedMetaG_metadata %>%
  select(age,age_category,non_westernized,BMI) %>%
  merge(enterotypes_curated, by="row.names") %>%
  mutate(bmi_cat = case_when(BMI<18.5~ "underweight",
                                                BMI>=18.5 & BMI<25 ~ "Normal",
                                                BMI>=25 & BMI<30 ~ "Overweight",
                                                BMI>=30 ~ "Obese")) %>%
  filter(age_category != "newborn") %>%
  filter(!is.na(bmi_cat)) %>%
  filter(non_westernized=="no") %>%
  group_by(bmi_cat) %>%
  mutate(total=n()) %>%
  group_by(bmi_cat,Enterotypes_id,total) %>%
  summarise(prop=n()) %>%
  mutate(prop=prop/total) %>%
  ungroup() %>%
  group_by(Enterotypes_id) %>%
  mutate(prop2=sum(prop)) %>%
  mutate(prop=prop/prop2) %>%
  ggplot() + geom_tile(aes(x=Enterotypes_id %>% as.character(),y=bmi_cat,fill=prop)) + scale_fill_viridis_c()



```



```{r fig.height=10, fig.width=10}

merge(df_curated,df_gutzilla, by="row.names") %>% 
  select(contains("m",ignore.case = TRUE)) %>% 
  select(-Mean.x,-Mean.y) %>%
  mutate(Row.names = Row.names %>% str_split_fixed(pattern =";",  n = 6) %>% .[,6]) %>%
  tibble::column_to_rownames("Row.names") %>% 
  as.matrix %>% 
  heatmap(scale = "column")

merge(df_curated,df_gutzilla, by="row.names") %>% 
  select(contains("m",ignore.case = TRUE)) %>% 
  select(-Mean.x,-Mean.y) %>%
  mutate(Row.names = Row.names %>% str_split_fixed(pattern =";",  n = 6) %>% .[,6]) %>%
  tibble::column_to_rownames("Row.names") %>% 
  as.matrix %>% 
  heatmap(scale = "row")



```

```{r}



```


```{r}

enterotypes_curated

enterotypes_alpha_div %>% head

alpha_shannon_curated %>% 
  merge(enterotypes_curated, by="row.names") %>%
  ggplot() + geom_boxplot(aes(x=Enterotypes_id%>%as.character,y=x))


bind_rows(alpha_shannon_curated %>% 
  merge(enterotypes_curated, by="row.names") %>%
  mutate(Enterotypes_id=paste0("M",Enterotypes_id)) %>%
  group_by(Enterotypes_id) %>%
  summarise(Shannon=median(x)) %>%
  ungroup() %>%
  mutate(rank=rank(Shannon), scale=scale(Shannon)),


enterotypes_alpha_div %>%
  mutate(Enterotypes_id=paste0("m",Enterotypes_id)) %>%
  group_by(Enterotypes_id) %>%
  summarise(Shannon=median(shannon)) %>%
  ungroup() %>%
  mutate(rank=rank(Shannon), scale=scale(Shannon))) -> microbiota_types_alpha_diversity


```



```{r fig.height=5, fig.width=10}

merge(df_curated,df_gutzilla, by="row.names") %>% 
  select(contains("m",ignore.case = TRUE)) %>% 
  select(-Mean.x,-Mean.y, -Row.names) %>% 
  colnames() %>%
  tibble::tibble(Microbiota=.) %>%
  mutate(dataset=ifelse(Microbiota %>% grepl("M", .), "CuratedMGdb","AGP")) %>%
  #mutate(random=rnorm(18+19)) %>%
  merge(microbiota_types_alpha_diversity, by.x="Microbiota", by.y="Enterotypes_id") %>%
  select(-rank, -Shannon) %>%
  dplyr::rename(`Shannon scaled`="scale") %>%
  merge(diet_coa, by.x="Microbiota", by.y ="row.names", all = TRUE ) %>%
  #select(-Axis2) %>%
  #dplyr::rename
  tibble::column_to_rownames("Microbiota") -> microbiota_annotation


merge(df_curated,df_gutzilla, by="row.names") %>% 
  select(contains("m",ignore.case = TRUE)) %>% 
  select(-Mean.x,-Mean.y) %>%
  mutate(Row.names = Row.names %>% str_split_fixed(pattern =";",  n = 6) %>% .[,6] %>% gsub("g__","",.)) %>%
  tibble::column_to_rownames("Row.names") %>% as.matrix() -> microbiota_types

microbiota_types_jsd = Rfast::Dist(t(microbiota_types)) 
colnames(microbiota_types_jsd) = row.names(microbiota_types_jsd) = colnames(microbiota_types)

microbiota_types_jsd = microbiota_types_jsd %>% as.dist() %>% sqrt()

ann_colors = list(
    dataset = c(AGP="pink", CuratedMGdb="lightblue"),
    `Shannon scaled` = RColorBrewer::brewer.pal(4, name="OrRd"),
    Axis1 = RColorBrewer::brewer.pal(4, name="BrBG"),
    Axis2 = RColorBrewer::brewer.pal(4, name="BrBG")
)


  #as.matrix %>% #log10() %>%
  pheatmap::pheatmap(mat=microbiota_types, cutree_cols = 6, annotation_col = microbiota_annotation, cellwidth = 10, cellheight = 20, clustering_distance_cols = microbiota_types_jsd, annotation_colors = ann_colors)



```



