---
title: "AGP notebook : diversity"
output: html_notebook
---


```{r}
library(ggplot2)
library(dplyr)
devtools::load_all()



```


```{r}

data("DWH_F_STR_DIV_clean")
data("nb_reads_estimated")
data("DWH_R_STR_SEQ_clean")

#merge(DWH_F_STR_DIV_clean, nb_reads_estimated, by="seq_id")



DWH_F_STR_DIV_clean %>%
  merge(DWH_R_STR_SEQ_clean , by="seq_id") %>%
  mutate(or_res_val=or_res_val %>% as.numeric) %>%
  ggplot() + geom_histogram(aes(x=or_res_val, fill=spe_val)) + facet_wrap(~test_cod, scales = "free")




DWH_F_STR_DIV_clean %>%
  merge(DWH_R_STR_SEQ_clean , by="seq_id") %>%
  merge(nb_reads_estimated, by ="seq_id") %>%
  mutate(or_res_val=or_res_val %>% as.numeric) %>%
  filter(est_n_seq > 50000) %>%
  ggplot() + geom_boxplot(aes(y=or_res_val, x=spe_val)) + 
  facet_wrap(~test_cod, scales = "free") + scale_y_log10() + coord_flip() 





```





```{r}

DWH_R_STR_SEQ_clean %>%
  filter(spe_val == "Stool") %>%
  merge(.,DWH_R_STR_DM_clean, by=c("seq_id","sub_id")) %>%
  as_tibble %>%
  filter(hst_tax_id==9606, thn_val == "Illumina MiSeq") %>%
  merge(DWH_F_STR_DIV_clean, by="seq_id") %>%
  group_by(seq_id,sub_id,age_val,test_cod) %>%
  mutate(or_res_val=or_res_val %>% as.numeric) %>%
  summarize(or_res_val=median(or_res_val)) %>%
  filter(age_val != "Miissing") %>% 
  ungroup() %>%
  mutate(age_val = age_val %>% as.character %>% as.numeric) %>%
  ggplot() + geom_point(aes(x=age_val,y=or_res_val),size=1,alpha=0.2) + facet_wrap(~test_cod, scale = "free") + geom_smooth(aes(x=age_val,y=or_res_val))
  








```




```{r}

DWH_R_STR_SEQ_clean %>%
  filter(spe_val == "Stool") %>%
  merge(.,DWH_R_STR_DM_clean, by=c("seq_id","sub_id")) %>%
  as_tibble %>%
  filter(hst_tax_id==9606, thn_val == "Illumina MiSeq") %>%
  merge(DWH_F_STR_DIV_clean, by="seq_id") %>%
  group_by(seq_id,sub_id,age_val,test_cod) %>%
  mutate(or_res_val=or_res_val %>% as.numeric) %>%
  summarize(or_res_val=median(or_res_val)) %>%
  filter(age_val != "Miissing") %>% 
  ungroup() %>%
  mutate(age_val = age_val %>% as.character %>% as.numeric) %>%
  filter(age_val < 5) %>%
  ggplot() + 
  geom_point(aes(x=age_val,y=or_res_val),size=1,alpha=0.2) + 
  facet_wrap(~test_cod, scale = "free") #+ geom_smooth(aes(x=age_val,y=or_res_val))




```



```{r}
data("DWH_R_STR_DM_clean")
data("DWH_F_STR_TXN_clean")
data("DWH_F_STR_SC_country")

DWH_F_STR_TXN_clean %>%
  
  filter(gen_val == "Bilophila") %>%
  reshape2::dcast(seq_id~gen_val, value.var = "or_res_val", fill=0) %>%
   merge(.,DWH_F_STR_SC_country, by="seq_id") %>% 
  as_tibble %>%
  #pull(BTH_CTRY) %>% table %>% sort %>% rev
  #mutate(Prevotella = log10(Prevotella + 10^-6)) %>%
  filter(BTH_CTRY %in% c("United States","United Kingdom", "India", "Australia")) %>%
  ggplot() + geom_histogram(aes(x=Bilophila + 10^-6, fill=BTH_CTRY), bins=30) + scale_x_log10() + facet_wrap(~BTH_CTRY, scales ="free_y")
  
  
  

```





