---
title: "enterobranches vs time-series"
output: html_notebook
---




```{r}

library(dplyr)
library(ggplot2)
devtools::load_all(reset = FALSE)




```


```{r}


enterotypes = readr::read_csv2("enterotypes_prediction_outliers.csv")[,-1]

metadata=read.csv2(system.file("data-raw/Metadata_10317_20191022-112414_curatedv4_VSv1.csv", package = "gutzilla"), stringsAsFactors = FALSE) %>% mutate_all(na_if,"")

shannon_path = system.file("data-raw/qiime/generated-files-20190512/alpha/shannon.qza", package = "gutzilla")

shannon = qiime2R::read_qza(shannon_path)$data %>% as.data.frame

```

```{r}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  group_by(HOST_SUBJECT_ID) %>%
  summarise(n=n()) %>%
  filter(n>1) %>%
  pull(n) %>% table



metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  mutate(sample_order=rank(days)) %>% 
  ggplot() + geom_line(aes(x=days,y=sample_order, group=HOST_SUBJECT_ID)) + scale_y_log10()



```



```{r}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  mutate(sample_order=rank(days)) %>% 
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  mutate(sample_order=rank(days)) %>% 
  xtabs(~ branches + HOST_SUBJECT_ID, data=.) %>%
  as.data.frame %>%
  filter(Freq!=0)



metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>% 
  filter(any(days==0)) %>% 
  filter(sample_order>1 & days <25) %>% 
  ggplot() + geom_tile(aes(x=sample_order,y=HOST_SUBJECT_ID, fill=branches)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + facet_wrap(~days_0, scales="free_y")




```


```{r}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  ggplot() + geom_point(aes(x=days +1,y=HOST_SUBJECT_ID, col=branches), shape=15) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + facet_wrap(~days_0, scales="free_y") + scale_x_log10()
 

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  filter(days > 0, days<365) %>%
  ungroup() %>%
  select(days_0,branches) %>% 
  xtabs(~days_0+branches, data=.) %>% prop.table(1)





```






```{r}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(HOST_SUBJECT_ID, days, sample_order, branches) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), branches_before=lag(branches), days_delta= days - lag(days)) %>% 
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  ggplot() + geom_boxplot(aes(x=branches_pairs, y=days_delta+1)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ 
  scale_y_log10() + facet_wrap(~branches_before, scales = "free", nrow=1)




```



```{r}


metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(HOST_SUBJECT_ID, days, sample_order, branches) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), branches_before=lag(branches), days_delta= days - lag(days)) %>% 
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  mutate(days_delta_bins = cut(days_delta, breaks = c(-1,60*60*24,120*24*60*60,365*60*60*24,10000*60*60*24))) %>%
  ggplot() + geom_bar(aes(x=days_delta_bins, fill=branches), position="fill") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_y_continuous(labels = scales::percent) + scale_fill_brewer("branches after", type="qual") +
  facet_wrap(~branches_before) + xlab("time range between two samples") + ylab("Samples %") + scale_x_discrete(labels=c("day","4 months", "4 to 12 months", "> 12 months"))


```
## compute prevotella bacteroides ratio within days
```{r}


genus_path = system.file("data-raw/qiime/generated-files-20190512/taxa/genus.qza", package = "gutzilla")
genus = qiime2R::read_qza(genus_path)$data %>% as.data.frame %>% tibble::rownames_to_column("taxa")  %>% as_tibble()

genus %>% 
  filter(taxa %in% c("k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides",
                     "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella")) %>%
  tibble::column_to_rownames("taxa") %>%
  t() %>%
  as.data.frame() -> TS_agp_genus_P_B


metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME,days, COLLECTION_TIMESTAMP) -> host_sample_days


host_sample_days %>%
  merge(host_sample_days, by="HOST_SUBJECT_ID") %>%
  filter(!(SAMPLE_NAME.x==SAMPLE_NAME.y)) %>%
  filter(days.y>days.x) %>%
  mutate(days_delta = days.y-days.x) %>%
  filter(days_delta <= 60*60*24) -> host_sample_pairs_within_days






metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME,Enterotypes_id,branches,COLLECTION_TIMESTAMP) -> host_sample_enterotypes_branches
  
  
host_sample_pairs_within_days %>%
  merge(host_sample_enterotypes_branches, by.x=c("HOST_SUBJECT_ID","SAMPLE_NAME.x", "COLLECTION_TIMESTAMP.x"), by.y=c("HOST_SUBJECT_ID","SAMPLE_NAME","COLLECTION_TIMESTAMP")) %>%
  merge(host_sample_enterotypes_branches, by.x=c("HOST_SUBJECT_ID","SAMPLE_NAME.y", "COLLECTION_TIMESTAMP.y"), by.y=c("HOST_SUBJECT_ID","SAMPLE_NAME","COLLECTION_TIMESTAMP")) %>%
  merge(TS_agp_genus_P_B, by.x="SAMPLE_NAME.x", by.y="row.names") %>%
  merge(TS_agp_genus_P_B, by.x="SAMPLE_NAME.y", by.y="row.names") %>%
  dplyr::rename(Bacteroides1 = "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides.x",
                Prevotella1  = "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella.x",
                Bacteroides2 = "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides.y",
                Prevotella2  = "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella.y") %>%
  mutate(PB_ratio_1 = log2((Prevotella1+1)/(Bacteroides1+1)), PB_ratio_2 = log2((Prevotella2+1)/(Bacteroides2+1))) %>%
  mutate(delta = PB_ratio_2-PB_ratio_1) -> host_sample_enterotypes_branches_P_B_ratio

host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  ggplot() + geom_bar(aes(x=paste(branches.x), fill=branches.y)) + coord_flip()



host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  ggplot() + geom_boxplot(aes(y=delta, branches.x, fill=branches.y))



host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  ggplot() + 
  geom_point(aes(x=PB_ratio_1, y=PB_ratio_2, color=paste(branches.x,"->",branches.y), size=days_delta < 1*60*60)) +
  geom_abline(slope=1,intercept = 0) +
  geom_abline(slope=1,intercept = -2.5, linetype=2) +
  geom_abline(slope=1,intercept = 2.5, linetype=2) +
  xlab("P/B ratio 1st sample") + ylab("P/B ratio 2nd sample") +
  scale_size_discrete("less than\n60 minutes") +
  scale_colour_discrete("")
  
  
  host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  filter(branches.x %in% "Prevotella DMM types") %>%
    mutate(less_than_one_hour = days_delta < 1*60*60) %>%
    xtabs(~branches.y + less_than_one_hour, data=.) #%>% chisq.test()
    
 
  host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  filter(branches.x %in% "Bacteroides DMM types") %>%
    mutate(less_than_one_hour = days_delta < 1*60*60) %>%
    xtabs(~branches.y + less_than_one_hour, data=.) #%>% chisq.test()
  
       

```

check stool collet daily time

```{r}


host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  ggplot() + 
  geom_point(aes(x=PB_ratio_1, y=PB_ratio_2, color=paste(branches.x,"->",branches.y), size=days_delta < 1*60*60)) +
  geom_abline(slope=1,intercept = 0) +
  geom_abline(slope=1,intercept = -2.5, linetype=2) +
  geom_abline(slope=1,intercept = 2.5, linetype=2) +
  xlab("P/B ratio 1st sample") + ylab("P/B ratio 2nd sample") +
  scale_size_discrete("less than\n60 minutes") +
  scale_colour_discrete("")

host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  mutate(hours.x=COLLECTION_TIMESTAMP.x %>% lubridate::hour(), hours.y=COLLECTION_TIMESTAMP.y %>% lubridate::hour()) %>%
  mutate(daytime = ifelse(hours.x < 12 & hours.y < 12, "both morning", ifelse(hours.x >= 12 & hours.y >= 12, "both afternoon", "no"))) %>%
  ggplot() + 
  geom_point(aes(x=PB_ratio_1, y=PB_ratio_2, color=daytime)) +
  geom_abline(slope=1,intercept = 0) +
  geom_abline(slope=1,intercept = -2.5, linetype=2) +
  geom_abline(slope=1,intercept = 2.5, linetype=2) +
  xlab("P/B ratio 1st sample") + ylab("P/B ratio 2nd sample") +
  scale_size_discrete("less than\n60 minutes") +
  scale_colour_discrete("")
 




host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  mutate(hours.x=COLLECTION_TIMESTAMP.x %>% lubridate::hour(), hours.y=COLLECTION_TIMESTAMP.y %>% lubridate::hour()) %>%
  mutate(daytime = ifelse(hours.x < 12 & hours.y < 12, "both morning", ifelse(hours.x >= 12 & hours.y >= 12, "both afternoon", "no"))) %>%
  filter(branches.x=="Prevotella DMM types"|branches.y=="Prevotella DMM types") %>%
  ggplot() +
  geom_boxplot(aes(fill=paste(branches.x,"->",branches.y),y=(PB_ratio_1+PB_ratio_2)/2,x=daytime)) +
  coord_flip()


host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  mutate(hours.x=COLLECTION_TIMESTAMP.x %>% lubridate::hour(), hours.y=COLLECTION_TIMESTAMP.y %>% lubridate::hour()) %>%
  mutate(daytime = ifelse(hours.x < 12 & hours.y < 12, "both morning", ifelse(hours.x >= 12 & hours.y >= 12, "both afternoon", "no"))) %>%
  filter(branches.x=="Prevotella DMM types"|branches.y=="Prevotella DMM types") %>%
  ggplot() +
  geom_bar(aes(x=paste(branches.x,"->",branches.y), fill=daytime), position="fill" ) + xlab("") + coord_flip() 

host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  mutate(hours.x=COLLECTION_TIMESTAMP.x %>% lubridate::hour(), hours.y=COLLECTION_TIMESTAMP.y %>% lubridate::hour()) %>%
  mutate(daytime = ifelse(hours.x < 12 & hours.y < 12, "both", ifelse(hours.x >= 12 & hours.y >= 12, "both", "no"))) %>%
  filter(branches.x=="Prevotella DMM types"|branches.y=="Prevotella DMM types") %>%
  ggplot() +
  geom_bar(aes(x=paste(branches.x,"->",branches.y), fill=daytime), position="fill" ) + xlab("") + coord_flip()


host_sample_enterotypes_branches_P_B_ratio %>%
  filter(branches.x %in% c("Bacteroides DMM types","Prevotella DMM types"),
         branches.y %in% c("Bacteroides DMM types","Prevotella DMM types")) %>%
  mutate(hours.x=COLLECTION_TIMESTAMP.x %>% lubridate::hour(), hours.y=COLLECTION_TIMESTAMP.y %>% lubridate::hour()) %>%
  mutate(daytime = ifelse(hours.x < 12 & hours.y < 12, "both", ifelse(hours.x >= 12 & hours.y >= 12, "both", "no"))) %>%
  filter(branches.x=="Prevotella DMM types"|branches.y=="Prevotella DMM types") %>%
  xtabs(~ paste(branches.x,"->",branches.y) + daytime, data=.) %>%
  chisq.test()


```



```{r}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_date()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(SAMPLE_NAME, HOST_SUBJECT_ID, days, sample_order, branches) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), branches_before=lag(branches), days_delta= days - lag(days)) %>% 
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  mutate(days_delta_bins = cut(days_delta, breaks = c(0,7,30,120,365,10000))) %>%
  ungroup() %>%
  filter(is.na(days_delta_bins))



```


```{r}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>% 
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(SAMPLE_NAME, HOST_SUBJECT_ID, days, sample_order, branches, COLLECTION_TIMESTAMP)


```

```{r fig.height=8, fig.width=10}

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  merge(shannon, by.x="SAMPLE_NAME", by.y="row.names") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>%
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(HOST_SUBJECT_ID, days, sample_order, branches, Enterotypes_id, shannon) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character ) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), 
         branches_before=lag(branches), days_delta= days - lag(days), 
         Enterotypes_id_before = lag(Enterotypes_id %>% as.character),
         shannon_before = lag(shannon)) %>%
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  mutate(days_delta_bins = cut(days_delta, breaks = c(-1,60*60*24,120*24*60*60,365*60*60*24,10000*60*60*24))) %>%
  filter(branches_before == "Bacteroides DMM types", branches == "Bacteroides DMM types") %>%
  
  select(shannon_before,shannon,Enterotypes_id,Enterotypes_id_before) %>%
    ungroup() %>%
  group_by(Enterotypes_id,Enterotypes_id_before) %>%
  summarise(shannon=median(shannon), shannon_before=median(shannon_before), n_p=n()) %>%
  ungroup() %>%
  group_by(Enterotypes_id_before) %>%
  mutate(prop_n_p = n_p/sum(n_p)) %>%
  group_by(Enterotypes_id_before) %>%
  arrange(Enterotypes_id_before, desc(prop_n_p)) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% factor(level=c("2","4","3","10","8","6","15","11")),
         Enterotypes_id_before = Enterotypes_id_before %>% factor(level=c("2","4","3","10","8","6","15","11"))) %>% 
  mutate(shannon_sens = shannon_before> shannon, enterotype_sens = as.numeric(Enterotypes_id_before) > as.numeric(Enterotypes_id)) -> Bacteroides_enterotypes_shannon_pairs 




metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  merge(shannon, by.x="SAMPLE_NAME", by.y="row.names") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>%
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(HOST_SUBJECT_ID, days, sample_order, branches, Enterotypes_id, shannon) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character ) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), 
         branches_before=lag(branches), days_delta= days - lag(days), 
         Enterotypes_id_before = lag(Enterotypes_id %>% as.character),
         shannon_before = lag(shannon)) %>%
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  mutate(days_delta_bins = cut(days_delta, breaks = c(-1,60*60*24,120*24*60*60,365*60*60*24,10000*60*60*24))) %>%
  filter(branches_before == "Prevotella DMM types", branches == "Prevotella DMM types") %>%
  
  select(shannon_before,shannon,Enterotypes_id,Enterotypes_id_before) %>%
    ungroup() %>%
  group_by(Enterotypes_id,Enterotypes_id_before) %>%
  summarise(shannon=median(shannon), shannon_before=median(shannon_before), n_p=n()) %>%
  ungroup() %>%
  group_by(Enterotypes_id_before) %>%
  mutate(prop_n_p = n_p/sum(n_p)) %>%
  group_by(Enterotypes_id_before) %>%
  arrange(Enterotypes_id_before, desc(prop_n_p)) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% factor(level=c("7","17","16","14","18")),
         Enterotypes_id_before = Enterotypes_id_before %>% factor(level=c("7","17","16","14","18"))) %>% 
  mutate(shannon_sens = shannon_before> shannon, enterotype_sens = as.numeric(Enterotypes_id_before) > as.numeric(Enterotypes_id)) -> Prevotella_enterotypes_shannon_pairs 



cowplot::plot_grid(
Bacteroides_enterotypes_shannon_pairs %>%
  ungroup() %>%
  filter(!(Enterotypes_id==Enterotypes_id_before)) %>%
  group_by(Enterotypes_id_before) %>%
  arrange(Enterotypes_id_before, desc(n_p)) %>%
  slice(1:2) %>%
  ggplot() + 
  geom_segment(aes(y=shannon_before, 
        yend=shannon, 
        x=Enterotypes_id_before %>% factor(level=c("2","4","3","10","8","6","15","11")), 
        xend=Enterotypes_id %>% factor(level=c("2","4","3","10","8","6","15","11")), 
        color=enterotype_sens), 
    arrow = arrow(length = unit(0.1,"cm"))) +
  ggrepel::geom_text_repel(aes(x=Enterotypes_id_before %>% factor(level=c("2","4","3","10","8","6","15","11")),
                y=shannon_before,
                label=round(prop_n_p,2) %>% scales::percent(accuracy=1))) +
  xlab("Bacteroides branch partition\nordered by PHATE centroid position") +
  ylab("alpha-diversity\n(Shannon)") +
  scale_color_discrete("", labels=c("toward branch-tip", "toward branch-root")),

Bacteroides_enterotypes_shannon_pairs %>%
  ungroup() %>%
  filter((Enterotypes_id==Enterotypes_id_before)) %>%
  ggplot() + 
  geom_bar(aes(x=Enterotypes_id_before,y=prop_n_p, fill=shannon), stat="identity") +
  scale_y_continuous(labels = scales::percent) +
  xlab("Bacteroides branch partition\nordered by PHATE centroid position") +
  ylab("stable participant sample-paired\nproportions"),





Prevotella_enterotypes_shannon_pairs %>%
  ungroup() %>%
  filter(!(Enterotypes_id==Enterotypes_id_before)) %>%
  group_by(Enterotypes_id_before) %>%
  arrange(Enterotypes_id_before, desc(n_p)) %>%
  slice(1:2) %>%
  ggplot() + 
  geom_segment(aes(y=shannon_before, 
        yend=shannon, 
        x=Enterotypes_id_before %>% factor(level=c("7","17","16","14","18")), 
        xend=Enterotypes_id %>% factor(level=c("7","17","16","14","18")), 
        color=enterotype_sens), 
    arrow = arrow(length = unit(0.1,"cm"))) +
  ggrepel::geom_text_repel(aes(x=Enterotypes_id_before %>% factor(level=c("7","17","16","14","18")),
                y=shannon_before,
                label=round(prop_n_p,2) %>% scales::percent(accuracy=1))) +
  xlab("Prevotella branch partition\nordered by PHATE centroid position") +
  ylab("alpha-diversity\n(Shannon)") +
  scale_color_discrete("", labels=c("toward branch-tip", "toward branch-root")),

Prevotella_enterotypes_shannon_pairs %>%
  ungroup() %>%
  filter((Enterotypes_id==Enterotypes_id_before)) %>%
  ggplot() + 
  geom_bar(aes(x=Enterotypes_id_before,y=prop_n_p, fill=shannon), stat="identity") +
  scale_y_continuous(labels = scales::percent) +
  xlab("Prevotella branch partition\nordered by PHATE centroid position") +
  ylab("stable participant sample-paired\nproportions"), nrow = 2, rel_widths = c(2,1))





```

## gut microbiota partitions networks based on times series 

```{r}
metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  merge(shannon, by.x="SAMPLE_NAME", by.y="row.names") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>%
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(HOST_SUBJECT_ID, days, sample_order, branches, Enterotypes_id, shannon) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character ) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), 
         branches_before=lag(branches), days_delta= days - lag(days), 
         Enterotypes_id_before = lag(Enterotypes_id %>% as.character),
         shannon_before = lag(shannon)) %>%
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  mutate(days_delta_bins = cut(days_delta, breaks = c(-1,60*60*24,120*24*60*60,365*60*60*24,10000*60*60*24))) %>%
  ungroup() %>%
  #filter(days_delta_bins %in% c("(-1,8.64e+04]","(8.64e+04,1.04e+07]")) %>%
  group_by(Enterotypes_id_before,Enterotypes_id) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  arrange(Enterotypes_id_before,desc(n)) %>%
  group_by(Enterotypes_id_before) %>%
  mutate(p=n/sum(n)) %>%
  slice(1:3) -> enterotypes_time_series_network
   
enterotypes_time_series_network %>%
  group_by(Enterotypes_id_before) %>%
  summarise(p=sum(p)) %>% pull(p) %>% summary() # if you select the top 2 switches + stability (=>66% average)



enterotypes_time_series_network %>%
  filter(Enterotypes_id_before==Enterotypes_id) %>%
  select(Enterotypes_id_before,p) %>%
  dplyr::rename(stability=p, Enterotypes_id=Enterotypes_id_before)-> enterotypes_time_series_stability

enterotypes_time_series_network %>%
  filter(!(Enterotypes_id_before==Enterotypes_id)) %>%
  select(Enterotypes_id_before,Enterotypes_id, p) -> enterotypes_time_series_switch



enterotypes_time_series_stability %>%
  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")) -> enterotypes_time_series_stability
```


```{r}
library(igraph)
library(ggraph)


#igraph::graph.data.frame(enterotypes_time_series_switch)
graph <- igraph::graph_from_data_frame(enterotypes_time_series_switch)

V(graph)

V(graph)$stability <- enterotypes_time_series_stability$stability         
V(graph)$branches <-  enterotypes_time_series_stability$branches 
V(graph)$partition_names <-   enterotypes_time_series_stability$Enterotypes_id
  
ggraph(graph, weights=p, layout="stress") +
  geom_edge_fan(aes(alpha = p), arrow=arrow(angle = 20, length = unit(4, "mm")), end_cap = circle(3, 'mm')) + 
  #scale_alpha_ordinal("participants proportion") +
  #geom_node_point(aes(color=branches,size=stability*2)) +
  geom_node_label(aes(label=partition_names, fill=branches, size=stability)) + 
  scale_fill_brewer(type="qual") +
  scale_alpha_continuous("participants proportion")
  
  

```



## main switches and keystone species

main switches occurred between #6 and #2, #3 and #5


```{r}

#compute fprau/bacteroides ratio and merge

f_GG = "k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Ruminococcaceae;g__Faecalibacterium"
b_GG = "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides"

genus %>%
  filter(taxa %in% c(f_GG,b_GG)) %>%
  tibble::column_to_rownames("taxa") %>%
  t %>%
  as.data.frame() %>%
  dplyr::rename(Feacalibacterium=2,Bacteroides=1) %>%
  mutate(ratio=Feacalibacterium/Bacteroides) -> f_b_ratio

# metadata %>%
#   filter(SAMPLE_TYPE == "Stool") %>%
#   select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
#   mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
#   merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
#   merge(shannon, by.x="SAMPLE_NAME", by.y="row.names") %>%
#   filter(set != "outliers") %>%
#   filter(Enterotypes_id != 19) %>%
#   group_by(HOST_SUBJECT_ID) %>%
#   mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
#   filter(n>1) %>%
#   
#   mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
#   group_by(HOST_SUBJECT_ID) %>%
#   arrange(HOST_SUBJECT_ID, days) %>%
#   mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>%
#   filter(Enterotypes_id %in% c(2,6)) %>%
#   ggplot() + geom_line(aes(x=days,y=shannon,group=HOST_SUBJECT_ID, col=as.character(Enterotypes_id))) 
  

metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  merge(shannon, by.x="SAMPLE_NAME", by.y="row.names") %>%
  merge(f_b_ratio, by.x="SAMPLE_NAME", by.y="row.names") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>%
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(SAMPLE_NAME, HOST_SUBJECT_ID, days, sample_order, branches, Enterotypes_id, shannon, ratio) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character ) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), 
         branches_before=lag(branches), days_delta= days - lag(days), 
         Enterotypes_id_before = lag(Enterotypes_id %>% as.character),
         shannon_before = lag(shannon),
         ratio_before = lag(ratio)) %>%
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  filter(Enterotypes_id %in% c(2,6), Enterotypes_id_before %in% c(2,6)) %>%
  ungroup() %>%
  select(SAMPLE_NAME,Enterotypes_id,shannon,ratio, Enterotypes_id_before,shannon_before, ratio_before) %>%
  mutate(switch=paste(Enterotypes_id,Enterotypes_id_before)) -> df

df %>%
  mutate(delta_ratio = abs(log2(ratio_before) - log2(ratio))) %>%
  ggplot() + geom_boxplot(aes(x=switch,y=delta_ratio)) + 
  ylab("Faecalibacterium/Bacteroides ratio variation") + 
  xlab("") + theme_classic() + 
  scale_x_discrete(label=c("within","between","between","within"))

df %>%
  mutate(delta_ratio = abs(log2(ratio_before) - log2(ratio))) %>%
  with(.,pairwise.wilcox.test(delta_ratio,switch, data=.))


rbind(df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch, ratio) ,
      df %>% select(SAMPLE_NAME,Enterotypes_id_before,shannon_before, switch, ratio_before) %>% dplyr::rename(Enterotypes_id=Enterotypes_id_before,shannon=shannon_before, ratio=ratio_before)) %>% 
        mutate(SAMPLE_NAME = SAMPLE_NAME %>% forcats::fct_reorder(ratio)) %>%
  arrange(switch) %>%
  ggplot() + geom_line(aes(x=ratio,y=SAMPLE_NAME, group=SAMPLE_NAME, col=switch))  + theme(axis.text.y = element_blank()) + scale_x_continuous(trans = "log2") + facet_wrap(~switch, ncol=1, scale="free_y")

df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  merge(f_b_ratio, by.x="SAMPLE_NAME", by.y="row.names") %>%
  mutate(SAMPLE_NAME = SAMPLE_NAME %>% forcats::fct_reorder(Enterotypes_id%>%as.numeric)) %>%
  ggplot() + geom_density(aes(x=ratio, fill=switch), alpha=0.5)  + theme(axis.text.y = element_blank()) + scale_x_continuous(trans = "log2")


df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("2 2", "2 6")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  ggplot() + geom_boxplot(aes(x=switch, y=value)) + facet_wrap(~variable, scale="free")


df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("2 2", "2 6")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  group_by(variable) %>%
  tidyr::nest()  %>% 
  mutate(wilcox_test=purrr::map(data,~wilcox.test(.x$value~.x$switch)),
        tidy=purrr::map(wilcox_test, broom::tidy)) %>% 
      tidyr::unnest(tidy,.drop=TRUE) %>%
  arrange(p.value) %>%
  ungroup() %>%
  #mutate(p.value=p.adjust(p.value, method="fdr")) %>%
  filter(p.value<0.05) %>% select(variable,p.value) %>% write.csv2(file="metadata_link_22vs26.csv")


df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("6 6", "6 2")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  group_by(variable) %>%
  tidyr::nest()  %>% 
  mutate(wilcox_test=purrr::map(data,~wilcox.test(.x$value~.x$switch)),
        tidy=purrr::map(wilcox_test, broom::tidy)) %>% 
      tidyr::unnest(tidy,.drop=TRUE) %>%
  arrange(p.value) %>%
  ungroup() %>%
  #mutate(p.value=p.adjust(p.value, method="fdr"))%>%
  filter(p.value<0.05) %>% select(variable,p.value) %>% write.csv2(file="metadata_link_66vs62.csv")



library(caret)
set.seed(666)
train.control <- trainControl(method = "repeatedcv", 
                              summaryFunction=twoClassSummary,
                              number = 10, repeats = 5, classProbs=T, savePredictions = T)

df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("2 2", "2 6")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>% select(-SAMPLE_NAME,-Enterotypes_id) %>% mutate(switch = paste0("p",switch) %>% gsub("\\ ","",.) %>% as.factor)   -> df_22_26
  

# Train the model
suppressWarnings(model <- train(switch ~., data = df_22_26, method = "rf",
               trControl = train.control))
# Summarize the results
print(model)


library(pROC)
# Select a parameter setting
selectedIndices <- model$pred$mtry == 2
#selectedIndices <- model$pred$ncomp == 1
# Plot:
plot.roc(model$pred$obs[selectedIndices],
         model$pred$p26[selectedIndices])




```

```{r}
metadata %>%
  filter(SAMPLE_TYPE == "Stool") %>%
  select(HOST_SUBJECT_ID,SAMPLE_NAME, COLLECTION_TIMESTAMP) %>%
  
  mutate(COLLECTION_TIMESTAMP = COLLECTION_TIMESTAMP %>% lubridate::as_datetime()) %>%
  merge(enterotypes, by.x="SAMPLE_NAME", by.y="sample_name") %>%
  merge(shannon, by.x="SAMPLE_NAME", by.y="row.names") %>%
  merge(f_b_ratio, by.x="SAMPLE_NAME", by.y="row.names") %>%
  filter(set != "outliers") %>%
  filter(Enterotypes_id != 19) %>%
  group_by(HOST_SUBJECT_ID) %>%
  mutate(min_date = min(COLLECTION_TIMESTAMP), n=n()) %>%
  filter(n>1) %>%
  
  mutate(days=COLLECTION_TIMESTAMP - min_date) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  arrange(HOST_SUBJECT_ID, days) %>%
  mutate(sample_order=order(COLLECTION_TIMESTAMP)) %>% 
  

  mutate(branches = case_when(Enterotypes_id %in% c(18,14,16,17,7) ~ "Prevotella DMM types",
                              Enterotypes_id %in% c(11,15,6,8,10,3,4,2) ~ "Bacteroides DMM types",
                              Enterotypes_id %in% c(12,1,5,9) ~ "Clostridiales DMM types",
                              Enterotypes_id %in% c(13) ~ "Akkermansia DMM types",
                              TRUE ~ "outliers")
         ) %>%
  
  mutate(days_0=branches[which.min(sample_order)]) %>%
  #arrange(HOST_SUBJECT_ID)  %>% 
  #mutate(sample_order=rank(days)) %>%
  mutate(days = as.numeric(days)) %>%
  select(SAMPLE_NAME, HOST_SUBJECT_ID, days, sample_order, branches, Enterotypes_id, shannon, ratio) %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character ) %>% 
  group_by(HOST_SUBJECT_ID) %>%
  mutate(same_branches_lag = ifelse(branches == lag(branches), "yes","no"), 
         branches_before=lag(branches), days_delta= days - lag(days), 
         Enterotypes_id_before = lag(Enterotypes_id %>% as.character),
         shannon_before = lag(shannon),
         ratio_before = lag(ratio)) %>%
  filter(sample_order >1) %>%
  mutate(branches_pairs=paste0(branches_before,"-",branches)) %>%
  filter(Enterotypes_id %in% c(3,5), Enterotypes_id_before %in% c(3,5)) %>%
  ungroup() %>%
  select(SAMPLE_NAME,Enterotypes_id,shannon,ratio, Enterotypes_id_before,shannon_before, ratio_before) %>%
  mutate(switch=paste(Enterotypes_id,Enterotypes_id_before)) -> df

df %>%
  mutate(delta_ratio = abs(log2(ratio_before) - log2(ratio))) %>%
  ggplot() + geom_boxplot(aes(x=switch,y=delta_ratio)) + 
  ylab("Faecalibacterium/Bacteroides ratio variation") + 
  xlab("") + theme_classic() + 
  scale_x_discrete(label=c("within","between","between","within"))

df %>%
  mutate(delta_ratio = abs(log2(ratio_before) - log2(ratio))) %>%
  with(.,pairwise.wilcox.test(delta_ratio,switch, data=.))


rbind(df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch, ratio) ,
      df %>% select(SAMPLE_NAME,Enterotypes_id_before,shannon_before, switch, ratio_before) %>% dplyr::rename(Enterotypes_id=Enterotypes_id_before,shannon=shannon_before, ratio=ratio_before)) %>% 
        mutate(SAMPLE_NAME = SAMPLE_NAME %>% forcats::fct_reorder(ratio)) %>%
  arrange(switch) %>%
  ggplot() + geom_line(aes(x=ratio,y=SAMPLE_NAME, group=SAMPLE_NAME, col=switch))  + theme(axis.text.y = element_blank()) + scale_x_continuous(trans = "log2") + facet_wrap(~switch, ncol=1, scale="free_y")

df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  merge(f_b_ratio, by.x="SAMPLE_NAME", by.y="row.names") %>%
  mutate(SAMPLE_NAME = SAMPLE_NAME %>% forcats::fct_reorder(Enterotypes_id%>%as.numeric)) %>%
  ggplot() + geom_density(aes(x=ratio, fill=switch), alpha=0.5)  + theme(axis.text.y = element_blank()) + scale_x_continuous(trans = "log2")

df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("5 5", "5 3")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  ggplot() + geom_boxplot(aes(x=switch, y=value)) + facet_wrap(~variable, scale="free")

df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("5 5", "3 3")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  ggplot() + geom_boxplot(aes(x=switch, y=value)) + facet_wrap(~variable, scale="free")



df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("5 5", "5 3")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  group_by(variable) %>%
  tidyr::nest()  %>% 
  mutate(wilcox_test=purrr::map(data,~wilcox.test(.x$value~.x$switch)),
        tidy=purrr::map(wilcox_test, broom::tidy)) %>% 
      tidyr::unnest(tidy,.drop=TRUE) %>%
  arrange(p.value) %>%
  ungroup() %>%
#mutate(p.value=p.adjust(p.value, method="fdr")) %>%
  filter(p.value<0.05) %>% select(variable,p.value) %>% write.csv2(file="metadata_link_55vs53.csv")




df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("3 3", "3 5")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  group_by(variable) %>%
  tidyr::nest()  %>% 
  mutate(wilcox_test=purrr::map(data,~wilcox.test(.x$value~.x$switch)),
        tidy=purrr::map(wilcox_test, broom::tidy)) %>% 
      tidyr::unnest(tidy,.drop=TRUE) %>%
  arrange(p.value) %>%
  ungroup() %>%
  #mutate(p.value=p.adjust(p.value, method="fdr")) %>%
  filter(p.value<0.05) %>% select(variable,p.value) %>% write.csv2(file="metadata_link_33vs35.csv")






df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("3 3", "5 5")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>%
  reshape2::melt(id=c("SAMPLE_NAME","Enterotypes_id","switch")) %>%
  group_by(variable) %>%
  tidyr::nest()  %>% 
  mutate(wilcox_test=purrr::map(data,~wilcox.test(.x$value~.x$switch)),
        tidy=purrr::map(wilcox_test, broom::tidy)) %>% 
      tidyr::unnest(tidy,.drop=TRUE) %>%
  arrange(p.value) %>%
  ungroup() %>%
#mutate(p.value=p.adjust(p.value, method="fdr")) %>%
  filter(p.value<0.05) %>% select(variable,p.value) %>% write.csv2(file="metadata_link_33vs55.csv")






library(caret)
set.seed(666)
train.control <- trainControl(method = "repeatedcv", 
                              summaryFunction=twoClassSummary,
                              number = 10, repeats = 5, classProbs=T, savePredictions = T)

df %>% select(SAMPLE_NAME,Enterotypes_id,shannon, switch) %>%
  filter(switch %in% c("5 5", "5 3")) %>%
  merge(metadata_enterotypes_num %>% select(-Enterotypes_id) %>% mutate_all(as.numeric), by.x="SAMPLE_NAME", by.y="row.names") %>% select(-SAMPLE_NAME,-Enterotypes_id, -shannon) %>% mutate(switch = paste0("p",switch) %>% gsub("\\ ","",.) %>% as.factor)   -> df_55_53
  

# Train the model
suppressWarnings(model <- train(switch ~., data = df_55_53, method = "rf",
               trControl = train.control, preProc=c("center", "scale")))
# Summarize the results
print(model)

varImp(model, scale = FALSE, useModel=TRUE)
roc_imp <- filterVarImp(x = df_55_53 %>% select(-switch), y = df_55_53$switch)


library(pROC)
# Select a parameter setting
selectedIndices <- model$pred$mtry == 2
# Plot:
plot.roc(model$pred$obs[selectedIndices],
         model$pred$p55[selectedIndices])



  
  
```


