---
title: "Network analysis"
output: html_notebook
---





```{r setup}

library(dplyr)
library(ggplot2)
library(ade4)
library(phateR)



```

```{r}
devtools::load_all(reset = FALSE)
```



load genus abundance
```{r}

genus_path = system.file("data-raw/qiime/generated-files-20190512/taxa/genus.qza", package = "agp")

genus = qiime2R::read_qza(genus_path)$data %>% as.data.frame %>% tibble::rownames_to_column("taxa")  %>% as_tibble()


```

import outliers file
```{r}

outliers = readLines(con="outliers_samples.txt")

```

load enterotypes set from DMM analysis
```{r}

enterotypes = readr::read_csv2("enterotypes_prediction_outliers.csv")[,-1]

```

```{r}

metadata=read.csv2(system.file("data-raw/Metadata_10317_20191022-112414_curatedv4_VSv1.csv", package = "agp"), stringsAsFactors = FALSE, ) %>% mutate_all(na_if,"")


variable_to_remove= c("HEIGHT_CM", 
"WEIGHT_KG",
"SAMPLE_TYPE",
"BMI_CAT",
"HOST_SUBJECT_ID",
"ANONYMIZED_NAME",
"ASSIGNED_FROM_GEO",
"BIRTH_YEAR",
"DESCRIPTION",
"DNA_EXTRACTED",
"HEIGHT_UNITS",
"WEIGHT_UNITS",
"SCIENTIFIC_NAME",
"SURVEY_ID",
"TAXON_ID",
"WEIGHT_UNITS",
"VIOSCREEN_STATUS","PUBLIC","TITLE")


metadata$SUBSET_IBD %>% as.factor %>% summary

metadata %>% 
  filter(!is.na(AGE_YEARS)) %>%
  filter(!is.na(TYPES_OF_PLANTS)) %>%
  filter(!is.na(ANTIBIOTIC_HISTORY)) %>%
  filter(!is.na(COUNTRY_OF_BIRTH)) %>%
  filter(!is.na(DIET_TYPE)) %>%
  filter(!is.na(LACTOSE)) %>%
  filter(!is.na(ALCOHOL_FREQUENCY)) %>%
  filter(!is.na(IBD)) %>%
  filter(!is.na(SEX)) %>%
  filter(!is.na(BMI)) %>%
  filter(!is.na(RED_MEAT_FREQUENCY)) %>%
  filter(!is.na(WHOLE_GRAIN_FREQUENCY)) %>%
  filter(!is.na(VEGETABLE_FREQUENCY)) %>%
  filter(!is.na(MILK_CHEESE_FREQUENCY)) %>%
  filter(!is.na(MEAT_EGGS_FREQUENCY)) %>%
  filter(!is.na(PREPARED_MEALS_FREQUENCY)) %>%
  filter(!is.na(DRINKING_WATER_SOURCE)) %>%
  filter(!is.na(EXERCISE_FREQUENCY)) %>%
  filter(!is.na(FRUIT_FREQUENCY)) %>%
  filter(!is.na(ONE_LITER_OF_WATER_A_DAY_FREQUENCY)) %>%
  filter(!is.na(FERMENTED_PLANT_FREQUENCY)) %>%
  filter(!is.na(SUGARY_SWEETS_FREQUENCY)) %>%
  filter(!is.na(MILK_SUBSTITUTE_FREQUENCY)) %>%
  filter(!is.na(SMOKING_FREQUENCY)) %>%
  filter(!is.na(PROBIOTIC_FREQUENCY)) %>%
  filter(!is.na(SEAFOOD_FREQUENCY)) %>%
  filter(!is.na(HOMECOOKED_MEALS_FREQUENCY)) %>%
  filter(!is.na(HIGH_FAT_RED_MEAT_FREQUENCY)) %>%
  filter(!is.na(SUGAR_SWEETENED_DRINK_FREQUENCY)) %>%
  select(which(colMeans(is.na(.)) == 0)) %>%
  #dim
  summarise_all(funs(sum(is.na(.)))) %>%
  reshape2::melt() %>%
  arrange((value))



metadata %>% 
  filter(!is.na(AGE_YEARS)) %>%
  filter(!is.na(TYPES_OF_PLANTS)) %>%
  filter(!is.na(ANTIBIOTIC_HISTORY)) %>%
  filter(!is.na(COUNTRY_OF_BIRTH)) %>%
  filter(!is.na(DIET_TYPE)) %>%
  filter(!is.na(LACTOSE)) %>%
  filter(!is.na(ALCOHOL_FREQUENCY)) %>%
  filter(!is.na(IBD)) %>%
  filter(!is.na(SEX)) %>%
  filter(!is.na(BMI)) %>%
  filter(!is.na(RED_MEAT_FREQUENCY)) %>%
  filter(!is.na(WHOLE_GRAIN_FREQUENCY)) %>%
  filter(!is.na(VEGETABLE_FREQUENCY)) %>%
  filter(!is.na(MILK_CHEESE_FREQUENCY)) %>%
  filter(!is.na(MEAT_EGGS_FREQUENCY)) %>%
  filter(!is.na(PREPARED_MEALS_FREQUENCY)) %>%
  filter(!is.na(DRINKING_WATER_SOURCE)) %>%
  filter(!is.na(EXERCISE_FREQUENCY)) %>%
  filter(!is.na(FRUIT_FREQUENCY)) %>%
  filter(!is.na(ONE_LITER_OF_WATER_A_DAY_FREQUENCY)) %>%
  filter(!is.na(FERMENTED_PLANT_FREQUENCY)) %>%
  filter(!is.na(SUGARY_SWEETS_FREQUENCY)) %>%
  filter(!is.na(MILK_SUBSTITUTE_FREQUENCY)) %>%
  filter(!is.na(SMOKING_FREQUENCY)) %>%
  filter(!is.na(PROBIOTIC_FREQUENCY)) %>%
  filter(!is.na(SEAFOOD_FREQUENCY)) %>%
  filter(!is.na(HOMECOOKED_MEALS_FREQUENCY)) %>%
  filter(!is.na(HIGH_FAT_RED_MEAT_FREQUENCY)) %>%
  filter(!is.na(SUGAR_SWEETENED_DRINK_FREQUENCY)) %>%
  select(which(colMeans(is.na(.)) == 0)) %>% 
  select(    -contains("SUBSET"),-contains("BODY"),
    -contains("ENV_"),-contains("HOST"),
    -contains("PHYSICAL_SPECIMEN_"), -c(all_of(variable_to_remove))) %>% 
  mutate_all(function(x){ifelse(x=="Yes","true",ifelse(x=="No","false",x))}) %>%
  mutate_all(function(x){ifelse(x=="true",1,ifelse(x=="false",0,x))}) %>%
  reshape2::melt(id.vars=c("SAMPLE_NAME","COUNTRY_OF_BIRTH","AGE_YEARS","BMI")) %>%
  mutate(value = value %>% recode(
                            `Daily` = "30",
                            `Never` = "0",
                            `Never` = "0",
                            `Occasionally (1-2 times/week)` = "6",
                            `Rarely (a few times/month)` = "2",
                            `Rarely (less than once/week)` = "2",
                            `Regularly (3-5 times/week)` = "16",
                            `Less than 5` = "0",
                            `6 to 10` = "6",
                            `11 to 20` = "11",
                            `21 to 30` = "21",
                            `More than 30` = "30",
                            `6 months` = "182",
                            `I have not taken antibiotics in the past year.` = "548",
                            `Month` = "30",
                            `Week` = "7",
                            `Year` = "365",
                            `Diagnosed by a medical professional (doctor, physician assistant)` = "1",
                            `I do not have this condition` = "0",
                            `Diagnosed by an alternative medicine practitioner` = "0.5",
                            `Self-diagnosed` = "0.5"
                             
                             
                             )) %>%
  reshape2::dcast(SAMPLE_NAME+COUNTRY_OF_BIRTH+AGE_YEARS+BMI~variable) -> metadata_cleaned





```

```{r}

write.csv2(metadata_cleaned, file = "metadata_cleaned.csv2")

metadata_cleaned =
  read.csv2(file = "metadata_cleaned.csv2", row.names = 1) %>%
  #select(-SAMPLE_NAME, -COUNTRY_OF_BIRTH) %>%
  mutate(BMI = BMI %>% as.character %>% as.numeric(),
         IBD =  IBD %>% as.character %>% as.numeric())

library(ade4)

metadata_cleaned %>%
  select(-SAMPLE_NAME, -COUNTRY_OF_BIRTH) %>%
  dudi.mix(nf=10,scannf=FALSE) -> metadata_pca

metadata_pca$co %>%
  tibble::rownames_to_column("variable") %>%
  ggplot() + geom_text(aes(x=Comp1, y=Comp5, label=variable))



```



select based on top 30 read mass genus and remove outliers

```{r}


genus %>%
  #select(1:10) %>%
  mutate_at(-1, ~./sum(.)) -> genus_prop

top_genus_mass = 
  genus_prop %>% 
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% 
  as.matrix %>% 
  apply(1,sum) %>% 
  sort %>% rev %>% head(30)


genus %>%
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% .[names(top_genus_mass),]-> genus

genus_prop %>%
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% .[names(top_genus_mass),]-> genus_prop

genus %>% t %>% as.data.frame %>% readr::write_tsv("agp_genus_top_30.tsv")






```


merge genus and cleaned metadata

```{r}

metadata_cleaned %>%
  merge(genus %>% t %>% as.data.frame, by.x="SAMPLE_NAME", by.y="row.names") %>%
  tibble::column_to_rownames("SAMPLE_NAME") %>%
  select(contains("k__Bacteria")) %>% readr::write_tsv("genus_agp_netw.tsv")
   


metadata_cleaned %>%
  merge(genus %>% t %>% as.data.frame, by.x="SAMPLE_NAME", by.y="row.names") %>%
  tibble::column_to_rownames("SAMPLE_NAME") %>%
  select(-COUNTRY_OF_BIRTH) %>%
  merge(enterotypes %>% select(sample_name, Enterotypes_id) %>% mutate(Enterotypes_id = paste0("M",Enterotypes_id)), by.x="row.names", by.y="sample_name") %>%
  tibble::column_to_rownames("Row.names") %>%
  select(-contains("k__Bacteria")) %>% #readr::write_tsv("agp_netw_meta.tsv")
  #mutate_if(is.integer,as.numeric)
  mutate_if(is.integer,function(x){x+rnorm(1,mean=0,sd=0.00000001)}) %>% 
  mutate(IBD=IBD+rnorm(1,mean=0,sd=0.00000001)) %>% readr::write_tsv("agp_netw_meta.tsv")


```



without metadata

```{julia }

using FlashWeave
data_path = "agp_genus_top_30.tsv"
#meta_data_path = "HMP_SRA_gut_tiny_meta.tsv"
#netw_results = learn_network(data_path, meta_data_path, sensitive=true, heterogeneous=false,  n_obs_min=5)

netw_results = learn_network(data_path, sensitive=true, heterogeneous=true)

graph(netw_results)

save_network("network_output.edgelist", netw_results)




```

with metadata

```{julia }

using FlashWeave

data_path = "genus_agp_netw.tsv"
meta_data_path = "agp_netw_meta.tsv"
#netw_results = learn_network(data_path, meta_data_path, sensitive=true, heterogeneous=false,  n_obs_min=5)

netw_results = learn_network(data_path,meta_data_path, sensitive=true, heterogeneous=false, FDR=true)

graph(netw_results)

save_network("metadata_network_output.edgelist", netw_results)



```





```{r}

network=readr::read_tsv("network_output.edgelist", skip=2, comment = "#", col_names = FALSE)

network %>%
  arrange(desc(abs(X3)))

```

```{r}

network=readr::read_tsv("metadata_network_output.edgelist", skip=2, comment = "#", col_names = FALSE)

network %>%
  arrange(desc(abs(X3))) %>%
  filter(X1=="DIET_TYPE_Vegetarian"|X2=="DIET_TYPE_Vegetarian") %>%
  
  


```



