---
title: "analysis using PHATE"
output: html_notebook
---



```{r }

library(dplyr)
library(ggplot2)
library(ade4)
library(phateR)
devtools::load_all(reset = FALSE)


```



load genus abundance
```{r}

genus_path = system.file("data-raw/qiime/generated-files-20190512/taxa/genus.qza", package = "agp")

genus = qiime2R::read_qza(genus_path)$data %>% as.data.frame %>% tibble::rownames_to_column("taxa")  %>% as_tibble()


```

import outliers file
```{r}

outliers = readLines(con="outliers_samples.txt")

```

load enterotypes set from DMM analysis
```{r}

enterotypes = readr::read_csv2("enterotypes_prediction_outliers.csv")[,-1]

```



select based on top 30 read mass genus and remove outliers

```{r}


genus %>%
  #select(1:10) %>%
  mutate_at(-1, ~./sum(.)) -> genus_prop

top_genus_mass = 
  genus_prop %>% 
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% 
  as.matrix %>% 
  apply(1,sum) %>% 
  sort %>% rev %>% head(30)


genus %>%
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% .[names(top_genus_mass),]-> genus

genus_prop %>%
  select(-all_of(outliers)) %>%
  tibble::column_to_rownames("taxa") %>% .[names(top_genus_mass),]-> genus_prop



```


```{r}

#genus_L1 = phateR::library.size.normalize(genus %>% t)

genus_phate = 
  genus_prop %>%
  t() %>%
  merge(enterotypes %>% filter(set != "outliers", value>0.80) %>% select(sample_name), by.x="row.names", by.y="sample_name") %>% 
  tibble::column_to_rownames("Row.names") %>%
  phateR::phate(gamma=0, t=60, seed=666)




```


```{r}
genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character) %>%
  group_by(Enterotypes_id) %>%
  summarise(PHATE1=mean(PHATE1), PHATE2=mean(PHATE2)) -> enterotypes_phate_centroid

enterotypes_phate_centroid %>%
  arrange(PHATE1)

enterotypes_phate_centroid %>%
  arrange(PHATE2)

```


```{r}
genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  mutate(branch ="Clostridiales DMM types") %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(18,14,16,17,7), "Prevotella DMM types",branch)) %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(11,15,6,8,10,3,4,2), "Bacteroides DMM types",branch)) %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(13), "Akkermansia DMM types",branch)) %>%
  #filter(Enterotypes_id %in% c(11,15,6,8,10,3,4,2)) %>%
  ggplot() + geom_point(aes(x=PHATE1, y=PHATE2, col=branch), size=1, alpha=0.5) +
  scale_color_brewer("main taxa\nDMM types",type="qual") + theme_classic() +
  ggrepel::geom_label_repel(data = enterotypes_phate_centroid, aes(x=PHATE1, y=PHATE2, label=Enterotypes_id)) #+
  #facet_wrap(~branch)
  
  #+ facet_wrap(~Enterotypes_id%>%as.character)

#save(genus_phate, file="genus_phate.rda")
```

```{r}


genus_phate_clostridiales = 
  genus_prop %>%
  t() %>%
  merge(enterotypes %>% filter(set != "outliers", value>0.80) %>% select(sample_name,Enterotypes_id), by.x="row.names", by.y="sample_name") %>% 
  mutate(branch ="Clostridiales DMM types") %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(18,14,16,17,7), "Prevotella DMM types",branch)) %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(11,15,6,8,10,3,4,2), "Bacteroides DMM types",branch)) %>%
  filter(branch == "Clostridiales DMM types" ) %>%
  select(-Enterotypes_id, -branch) %>%
  tibble::column_to_rownames("Row.names") %>%
  phateR::phate(gamma=0, t=60, seed=666)





```



```{r}


genus_phate_clostridiales$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  mutate(Enterotypes_id = Enterotypes_id %>% as.character) %>%
  group_by(Enterotypes_id) %>%
  summarise(PHATE1=mean(PHATE1), PHATE2=mean(PHATE2)) -> enterotypes_phate_centroid

enterotypes_phate_centroid %>%
  arrange(PHATE1)

enterotypes_phate_centroid %>%
  arrange(PHATE2)

genus_phate_clostridiales$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  mutate(branch ="Clostridiales DMM types") %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(18,14,16,17,7), "Prevotella DMM types",branch)) %>%
  mutate(branch = ifelse(Enterotypes_id %in% c(11,15,6,8,10,3,4,2), "Bacteroides DMM types",branch)) %>%
  #filter(Enterotypes_id %in% c(11,15,6,8,10,3,4,2)) %>%
  ggplot() + geom_point(aes(x=PHATE1, y=PHATE2, col=Enterotypes_id%>%as.character), size=1, alpha=0.5) +
  scale_color_brewer("Clostridiales-Akkermansia\nDMM types",type="qual") + theme_classic() +
  ggrepel::geom_label_repel(data = enterotypes_phate_centroid, aes(x=PHATE1, y=PHATE2, label=Enterotypes_id)) #+
  #facet_wrap(~branch)
  
  #+ facet_wrap(~Enterotypes_id%>%as.character)

#save(genus_phate, file="genus_phate.rda")
```




compute bacteroides prevotella ratio

```{r}

genus_bact_prev_ratio =
genus %>% 
  #select(sample_select) %>%
  t %>% as.data.frame() %>% 
  tibble::rownames_to_column("sample_id") %>%
  select(sample_id, "k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides","k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella") %>%
  #head() %>%
  dplyr::rename(Bacteroides=2, Prevotella=3) %>%
  mutate(prev_bact_ratio = log2((Prevotella+1)/(Bacteroides+1))) %>%
  select(sample_id,prev_bact_ratio)


```



```{r}

genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  #merge(as.data.frame(genus_mada), by.x="Row.names", by.y="row.names") %>%
  merge(genus_bact_prev_ratio, by.x="Row.names", by.y="sample_id") %>%
  ggplot() + geom_point(aes(x=PHATE1, y=PHATE2, col=prev_bact_ratio), size=1, alpha=0.5) +
  scale_color_viridis_c() 

ggsave("genus_phate_prevotella_ratio.pdf")

```




import shannon
```{r}

shannon_path = system.file("data-raw/qiime/generated-files-20190512/alpha/shannon.qza", package = "agp")

shannon = qiime2R::read_qza(shannon_path)$data %>% as.data.frame

```

```{r}

genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  #merge(as.data.frame(genus_mada), by.x="Row.names", by.y="row.names") %>%
  merge(genus_bact_prev_ratio, by.x="Row.names", by.y="sample_id") %>%
  merge(shannon, by.x="Row.names", by.y="row.names") %>%
  ggplot() + geom_point(aes(x=PHATE1, y=PHATE2, col=shannon), size=1, alpha=0.5) +
  scale_color_viridis_c() 

ggsave("genus_phate_shannon.pdf")

```

explore bacteroides and prevotella path


```{r}

genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  #merge(as.data.frame(genus_mada), by.x="Row.names", by.y="row.names") %>%
  merge(genus_bact_prev_ratio, by.x="Row.names", by.y="sample_id") %>%
  merge(shannon, by.x="Row.names", by.y="row.names") %>%
  #filter(PHATE1<0) %>%
  mutate(PHATE1=PHATE1%>%rank()) %>%
  ggplot() + geom_density(aes(x=PHATE1, col=Enterotypes_id%>%as.character))


```




```{r fig.height=5, fig.width=12}


genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  #merge(as.data.frame(genus_mada), by.x="Row.names", by.y="row.names") %>%
  merge(genus_bact_prev_ratio, by.x="Row.names", by.y="sample_id") %>%
  merge(shannon, by.x="Row.names", by.y="row.names") %>%
  mutate(PHATE1=PHATE1%>%rank()) %>%
  mutate(bin = cut(PHATE1, seq(min(PHATE1), max(PHATE1) + 150, 150), right = FALSE)) %>% 
  group_by(bin) %>%
  summarise(prev_bact_ratio=median(prev_bact_ratio), shannon=median(shannon)) -> phate_richness_bins


genus_phate_enterotypes_plot=
genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  #merge(as.data.frame(genus_mada), by.x="Row.names", by.y="row.names") %>%
  merge(genus_bact_prev_ratio, by.x="Row.names", by.y="sample_id") %>%
  merge(shannon, by.x="Row.names", by.y="row.names") %>%
  mutate(PHATE1=PHATE1%>%rank()) %>%
  mutate(bin = cut(PHATE1, seq(min(PHATE1), max(PHATE1) + 150, 150), right = FALSE)) %>% 
  #group_by(bin) %>%
  ggplot() + geom_bar(aes(x=bin,fill=Enterotypes_id%>%as.character), position=position_fill(), width=1) + 
  theme_classic()+
  theme(axis.text.x = element_blank())
  
  genus_phate_enterotypes_plot
  ggsave(genus_phate_enterotypes_plot, file="genus_phate_enterotypes_plot.pdf", h=5, w=12)


```




```{r fig.height=3, fig.width=10}

phate_richness_plot=
phate_richness_bins %>% 
  reshape2::melt(id.vars=c("bin")) %>%
  group_by(variable) %>%
  mutate(value=scale(value)) %>%
  ggplot() + geom_tile(aes(x=bin,y=variable, fill=value)) + 
  scale_fill_viridis_c() +
  theme_classic()+
  theme(axis.text.x = element_blank())


phate_richness_plot
ggsave(phate_richness_plot,file="phate_richness_plot.pdf", h=2,w=10)



```

compare PHATE with genus
```{r fig.height=5, fig.width=15}

genus_path = system.file("data-raw/qiime/generated-files-20190512/taxa/genus.qza", package = "agp")

genus = qiime2R::read_qza(genus_path)$data %>% as.data.frame %>% tibble::rownames_to_column("taxa")  %>% as_tibble()



genus_alr_ranked=
genus %>%
  tibble::column_to_rownames("taxa") %>%
  SpiecEasi::alr(divcomp=1,removeDivComp=FALSE) %>% as.data.frame() %>%
  tibble::rownames_to_column("taxa") %>%
  reshape2::melt() %>%
  group_by(variable) %>%
  mutate(value=rank(value)) 

genus_alr_ranked =
  genus_alr_ranked %>%
  filter(taxa %in% names(top_genus_mass))

genus_phate_plot=
genus_phate$embedding %>%
  merge(enterotypes, by.x="row.names", by.y="sample_name") %>%
  mutate(PHATE1=PHATE1%>%rank()) %>%
  mutate(bin = cut(PHATE1, seq(min(PHATE1), max(PHATE1) + 150, 150), right = FALSE)) %>% 
  merge(genus_alr_ranked, by.x="Row.names", by.y="variable") %>%
  group_by(bin,taxa) %>%
  summarise(value=mean(value.y)) %>%
  mutate(taxa = factor(taxa, levels=names(top_genus_mass))) %>%
  ggplot() + geom_tile(aes(x=bin,y=taxa,fill=(value))) + 
  scale_fill_viridis_c() +
  theme_classic()+
  theme(axis.text.x = element_blank())



ggsave(genus_phate_plot, file="genus_phate_plot.pdf", w=15,h=5)

genus_phate_plot

```


combine plot


```{r fig.height=10, fig.width=20}

cowplot::plot_grid(
genus_phate_enterotypes_plot,

phate_richness_plot,

genus_phate_plot, ncol=1, align = "v", rel_heights = c(5,1,5))


ggsave(file="PHATE_combined_plot.pdf")

```






